// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

// NESTED INCLUDES

#include "enums/instructions.hpp"
#include "instructions/instruction.h"

using namespace catherine;

// ACCESS THE PROVIDED OPCODE NAME IN CONJUNCTION WITH THE PROVIDED API
// THE DIFFERENCE HERE IS THAT WE HAVE TO TYPE CAST ACCORDINGLY TO ACCESS
std::string GET_OPCODE_NAME(INSTR_ID::CATH_INSTR_ID_CXX UNIQUE)
{
    CATH_INSTR_ID ID = static_cast<CATH_INSTR_ID>(UNIQUE);
    return std::string(CATH_GET_OPCODE_NAME(ID));
}