// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

// NESTED INCLUDES

#include "enums/instructions.hpp"
#include "instructions/instruction.hpp"

// SYSTEM INCLUDES

#include <cstring>

using namespace catherine;

// EACH OF THE FOLLOWING CONSTRUCTORS HELPS WITH A SPECIFIC OP
// ONE DEFINES THE BASIS FOR ACCESSING EACH INSTRUCTION
//
// THE OTHER FOCUSSES ON ACCESSING THE CURRENT WORD AND PC ADDRESS FOR EACH
//
// ALWAYS USE &this FOR ACCESSING THE REFERENCE ASSOCIATED WITH THE CLASS
CATH_INSTRUCTION::CATH_INSTRUCTION()
{
    std::memset(&this->INSTR, 0, sizeof(SH_INSTRUCTION));
    this->INSTR.INSTR_ID = CATH_INSTR_ID_INVALID;
}

CATH_INSTRUCTION::CATH_INSTRUCTION(U16 WORD, U32 PC) noexcept
{
    std::memset(&this->INSTR, 0, sizeof(SH_INSTRUCTION));
    CATH_INSTRUCTION_INIT(&this->INSTR, WORD, PC);
    CATH_INSTRUCTION_PROCESS(&this->INSTR);
} 
