// COPYRIGHT (C) HARRY CLARK 2026
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS OF THE SCU DSP 

// NESTED INCLUDES

#include "enums/instructionsDSP.hpp"
#include "instructions/instructionDSP.hpp"

// SYSTEM INCLUDES

#include <cstring>
#include <cstdlib>

using namespace catherine;

CATH_INSTRUCTION_SCU_DSP::CATH_INSTRUCTION_SCU_DSP(U32 WORD, U32 ADDRESS)
{
    std::memset(&this->INSTR, 0, sizeof(SH_DSP_INSTRUCTION));
    CATH_DSP_INSTRUCTION_INIT(&this->INSTR, WORD, ADDRESS);
    CATH_DSP_INSTRUCTION_PROCESS(&this->INSTR);
}

std::string CATH_INSTRUCTION_SCU_DSP::CATH_INSTRUCTION_DSP::CATH_DSP_DISASSEMBLE_OPERANDS() const
{
    UNK SIZE = CATH_DSP_INSTRUCTION_DISASM_OPERAND(&this->INSTR, nullptr, 0);
    std::string RESULT(SIZE, '\0');

    CATH_DSP_INSTRUCTION_DISASM_OPERAND(&this->INSTR, RESULT.data(), SIZE + 1);
    return RESULT;
}

std::string CATH_INSTRUCTION_SCU_DSP::CATH_INSTRUCTION_DSP::CATH_DSP_DISASSEMBLE_INSTR() const
{
    UNK SIZE = CATH_DSP_INSTRUCTION_GET_SIZE(&this->INSTR);
    std::string RESULT(SIZE, '\0');

    CATH_DSP_INSTRUCTION_DISASM(&this->INSTR, RESULT.data(), SIZE + 1);
    return RESULT;
}
