// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS OF THE SCU DSP 

#ifndef CATH_INSTR_DSP_H
#define CATH_INSTR_DSP_H

#pragma once

// NESTED INCLUDES

#include "instructions/instruction.h"

#if defined(CATH_INSTR_DSP)
    #define CATH_INSTR_DSP
#else
    #define CATH_INSTR_DSP

#ifdef __cplusplus
extern "C" {
#endif

    // DEFINE THE BASIS FOR ACCESSING INSTRUCTION
    // TYPES AND THEIR CHARACTERISTICS
    typedef struct SH_DSP_INSTRUCTION
    {
        CATH_INSTR_ID INSTR_ID;
        const SH_DESCRIPTOR* DESCRIPTOR;
        
        U32 FLAGS;
        U32 PC;
        U32 WORD;

    } SH_DSP_INSTRUCTION;

    // PRE PROCESSOR DIRECTIVES TO HELP WITH ACCESS TO SPECIFIC CHARACTERISTICS CPU-WISE
    // ACCEES TO OPCODE WORD, FUNCTION ID AND CALLBACKS

    #define         SCU_DSP_GET_OPERAND(VALUE)                  (CATH_SHIFT_R((VALUE)->WORD, 26, 6))
    #define         SCU_DSP_PACK_OPERAND(WORD, VALUE)           (CATH_PACK_BITS((WORD), (VALUE), 26, 6))
}

#endif
#endif