// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE OPERANDS

#ifndef CATH_OPERANDS_H
#define CATH_OPERANDS_H

// NESTED INCLUDES  

#include <common.h>

#if defined(CATH_OPERAND)
    #define CATH_OPERAND
#else
    #define CATH_OPERAND

    struct SH_INSTRUCTION;

    typedef enum
    {
        OPERAND_NONE,
        OPERAND_IMM,
        OPERAND_RN,
        OPERAND_RM,
        OPERAND_AT_RN,
        OPERAND_AT_RM,
        OPERAND_AT_RM_POST_INC,
        OPERAND_AT_RN_POST_INC,
        OPERAND_AT_RN_PRE_DEC,
        OPERAND_AT_DISP_RN,
        OPERAND_AT_DISP_RM,
        OPERAND_AT_R0_RM,
        OPERAND_AT_R0_RN,
        OPERAND_AT_DISP_GBR,
        OPERAND_AT_R0_GBR,
        OPERAND_AT_RN_PC,
        OPERAND_AT_DISP_PC,
        OPERAND_AT_DISP_PC_ALIGN,
        OPERAND_DISP_PC,
        OPERAND_RN_PC,
        OPERAND_SR,
        OPERAND_GBR,
        OPERAND_VBR,
        OPERAND_MACH,
        OPERAND_MACL,
        OPERAND_PR,
        OPERAND_MAX

    } SH_OPERAND_TYPE;

    // FUNCTION CALLBACK FOR ACCESSING THE CURRENT OPERAND PER INSTRUCTION 
    // AND IT'S RELEVANT CHARACTERISTICS
    typedef UNK(*SH2_OPERAND_CALLBACK)(const struct SH_INSTRUCTION*, char*);

    extern const SH2_OPERAND_CALLBACK INSTR_CALLBACKS[];

    UNK CATH_OPERAND_TYPE_NONE(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_RM(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_RN(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_IMM(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RN(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RM(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RN_PRE_DEC(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RN_POST_INC(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_R0_RN(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_DISP_GBR(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_R0_GBR(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_DISP_PC(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_DISP_PC(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_SR(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_GBR(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_VBR(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_MACH(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_MACL(const SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_PR(const SH_INSTRUCTION*, char*, UNK);

#endif
#endif
