// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE DSP OPERANDS

#ifndef CATH_DSP_OPERANDS_H
#define CATH_DSP_OPERANDS_H

// NESTED INCLUDES  

#include <common.h>

#if defined(CATH_DSP_OPERAND)
    #define CATH_DSP_OPERAND
#else
    #define CATH_DSP_OPERAND

    struct SH_INSTRUCTION;
    struct SH_DSP_INSTRUCTION;

    typedef enum SH_DSP_OPERAND_TYPE
    {
        DSP_OPERAND_NONE,
        DSP_OPERAND_MC0,
        DSP_OPERAND_MC1,
        DSP_OPERAND_MC2,
        DSP_OPERAND_MC3,

        DSP_OPERAND_X,
        DSP_OPERAND_Y,
        DSP_OPERAND_P,

        DSP_OPERAND_MUL,
        DSP_OPERAND_ALU,
        DSP_OPERAND_A,
        DSP_OPERAND_ACC,
        DSP_OPERAND_MVI_DEST,
        DSP_OPERAND_MVI_IMM,
        DSP_OPERAND_MVI_COND,

        DSP_OPERAND_JMP_COND,

        DSP_OPERAND_RAM0_ADDR,
        DSP_OPERAND_RAM1_ADDR,
        DSP_OPERAND_RAM2_ADDR,
        DSP_OPERAND_RAM3_ADDR,

        DSP_OPERAND_RAM0_DATA,
        DSP_OPERAND_RAM1_DATA,
        DSP_OPERAND_RAM2_DATA,
        DSP_OPERAND_RAM3_DATA,

        DSP_OPERAND_CT0,
        DSP_OPERAND_CT1,
        DSP_OPERAND_CT2,
        DSP_OPERAND_CT3,

        DSP_OPERAND_RX,
        DSP_OPERAND_RY,

        DSP_OPERAND_STORE,
        DSP_OPERAND_PC,
        DSP_OPERAND_TOP,
        DSP_OPERAND_LOP,

        DSP_OPERAND_IMM,
        DSP_OPERAND_IMM_DISP,

        DSP_OPERAND_AT_RAM0_ADDR,
        DSP_OPERAND_AT_RAM1_ADDR,
        DSP_OPERAND_AT_RAM2_ADDR,
        DSP_OPERAND_AT_RAM3_ADDR,

        DSP_OPERAND_DMA,

        DSP_OPERAND_MAX

    } SH_DSP_OPERAND_TYPE;

    // FUNCTION CALLBACK FOR ACCESSING THE CURRENT OPERAND PER INSTRUCTION 
    // AND IT'S RELEVANT CHARACTERISTICS
    typedef UNK(*SH_DSP_OPERAND_CALLBACK)(const struct SH_DSP_INSTRUCTION* INSTR, char* DEST, UNK SIZE);

    extern const SH_DSP_OPERAND_CALLBACK DSP_INSTR_CALLBACKS[DSP_OPERAND_MAX];

    // FUNCTION PROTOTYPES FOR DSP OPERAND CHARACTERISTICS
    // USED FOR DISASSEMBLY

    UNK CATH_DSP_OPERAND_TYPE_GET_BUFFER_SIZE(SH_DSP_OPERAND_TYPE, const struct SH_DSP_INSTRUCTION*);
    UNK CATH_DSP_OPERAND_TYPE_DISASM(SH_DSP_OPERAND_TYPE, const struct SH_DSP_INSTRUCTION*, char*);

    // FUNCTION POINTERS TO ACCESS ENUM VALUES
    // MAP CORRESPONDING TO THEIR CHARACTERISTICS WITHIN THE LOOKUP TABLE

    UNK CATH_DSP_OPERAND_TYPE_NONE(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_MC0(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_MC1(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_MC2(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_MC3(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_X(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_Y(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_P(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_MUL(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_ALU(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_ACC(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_MVI_DEST(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_MVI_IMM(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_MVI_COND(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_JMP_COND(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_RAM0_ADDR(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RAM1_ADDR(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RAM2_ADDR(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RAM3_ADDR(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_RAM0(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RAM1(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RAM2(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RAM3(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_CT0(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_CT1(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_CT2(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_CT3(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RX(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_RY(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    
    UNK CATH_DSP_OPERAND_TYPE_ALL(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_PC(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_TOP(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_LOP(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_IMM(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_IMM_DISP(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_AT_RAM0_ADR(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_AT_RAM1_ADR(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_AT_RAM2_ADR(const struct SH_DSP_INSTRUCTION*, char*, UNK);
    UNK CATH_DSP_OPERAND_TYPE_AT_RAM3_ADR(const struct SH_DSP_INSTRUCTION*, char*, UNK);

    UNK CATH_DSP_OPERAND_TYPE_DMA(const struct SH_DSP_INSTRUCTION*, char*, UNK);

#endif
#endif
