// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE OPERANDS

#ifndef CATH_OPERANDS_H
#define CATH_OPERANDS_H

// NESTED INCLUDES  

#include <common.h>

#if defined(CATH_OPERAND)
    #define CATH_OPERAND
#else
    #define CATH_OPERAND

    typedef enum
    {
        OPERAND_NONE,
        OPERAND_IMM,
        OPERNAD_RN,
        OPERAND_AT_RN,
        OPERAND_AT_RN_POST_INC,
        OPERAND_AT_RN_PRE_DEC,
        OPERAND_AT_RN_DISP_RN,
        OPERAND_AT_R0_RN,
        OPERAND_AT_DISP_GBR,
        OPERAND_AT_R0_GBR,
        OPERAND_AT_RN_PC,
        OPERAND_AT_DISP_PC,
        OPERAND_AT_DISP_PC_ALIGN,
        OPERAND_DISP_PC,
        OPERAND_RN_PC,
        OPERAND_SR,
        OPERAND_GBR,
        OPERAND_VBR,
        OPERAND_MACH,
        OPERAND_MACL,
        OPERAND_PR,
        OPERAND_MAX

    } SH_OPERAND_TYPE;

#endif
#endif