// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE DSP OPERANDS

#ifndef CATH_DSP_OPERANDS_H
#define CATH_DSP_OPERANDS_H

// NESTED INCLUDES  

#include <common.h>

#if defined(CATH_DSP_OPERAND)
    #define CATH_DSP_OPERAND
#else
    #define CATH_DSP_OPERAND

    struct SH_DSP_INSTRUCTION;

    typedef enum SH_DSP_OPERAND_TYPE
    {
        DSP_OPERAND_NONE,
        DSP_OPERAND_MC0,
        DSP_OPERAND_MC1,
        DSP_OPERAND_MC2,
        DSP_OPERAND_MC3,

        DSP_OPERAND_X,
        DSP_OPERAND_Y,
        DSP_OPERAND_P,

        DSP_OPERAND_MUL,
        DSP_OPERAND_ALU,
        DSP_OPERAND_ACC,

        DSP_OPERAND_RAM0_ADDR,
        DSP_OPERAND_RAM1_ADDR,
        DSP_OPERAND_RAM2_ADDR,
        DSP_OPERAND_RAM3_ADDR,

        DSP_OPERAND_RAM0_DATA,
        DSP_OPERAND_RAM1_DATA,
        DSP_OPERAND_RAM2_DATA,
        DSP_OPERAND_RAM3_DATA,

        DSP_OPERAND_CT0,
        DSP_OPERAND_CT1,
        DSP_OPERAND_CT2,

        DSP_OPERAND_IMM,
    };

#endif
#endif
