// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE OPERANDS

#ifndef CATH_OPERANDS_H
#define CATH_OPERANDS_H

// NESTED INCLUDES  

#include <common.h>

#if defined(CATH_OPERAND)
    #define CATH_OPERAND
#else
    #define CATH_OPERAND

    struct SH_INSTRUCTION;
 
    typedef enum SH_OPERAND_TYPE
    {
        OPERAND_NONE,
        OPERAND_IMM,
        OPERAND_RN,
        OPERAND_RM,
        OPERAND_R0,
        OPERAND_AT_RN,
        OPERAND_AT_RM,
        OPERAND_AT_RM_POST_INC,
        OPERAND_AT_RN_POST_INC,
        OPERAND_AT_RN_PRE_DEC,
        OPERAND_AT_DISP_RN,
        OPERAND_AT_DISP_RM,
        OPERAND_AT_R0_RM,
        OPERAND_AT_R0_RN,
        OPERAND_AT_DISP_GBR,
        OPERAND_AT_R0_GBR,
        OPERAND_AT_RN_PC,
        OPERAND_AT_DISP_PC,
        OPERAND_AT_DISP_PC_ALIGN,
        OPERAND_DISP_PC,
        OPERAND_RN_PC,
        OPERAND_RM_PC,
        OPERAND_AT_IMM_RN_RM,
        OPERAND_SR,
        OPERAND_GBR,
        OPERAND_VBR,
        OPERAND_MACL,
        OPERAND_MACH,
        OPERAND_PR,
        OPERAND_MAX

    } SH_OPERAND_TYPE;

    // FUNCTION CALLBACK FOR ACCESSING THE CURRENT OPERAND PER INSTRUCTION 
    // AND IT'S RELEVANT CHARACTERISTICS
    typedef UNK(*SH2_OPERAND_CALLBACK)(const struct SH_INSTRUCTION* INSTR, char* DEST, UNK SIZE);

    extern const SH2_OPERAND_CALLBACK INSTR_CALLBACKS[OPERAND_MAX];

    // FUNCTION PROTOTYPES FOR OPERAND CHARACTERISTICS
    // USED FOR DISASSEMBLY

    UNK CATH_OPERAND_TYPE_GET_BUFFER_SIZE(SH_OPERAND_TYPE, const struct SH_INSTRUCTION*);
    UNK CATH_OPERAND_TYPE_DISASM(SH_OPERAND_TYPE, const struct SH_INSTRUCTION*, char*);

    // FUNCTION POINTERS TO ACCESS ENUM VALUES
    // MAP CORRESPONDING TO THEIR CHARACERISTICS WITHIN THE LOOKUP TABLE

    UNK CATH_OPERAND_TYPE_NONE(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_RM(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_RN(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_R0(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_IMM(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RN(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RM(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RM_POST_INC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RN_PRE_DEC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RN_POST_INC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_R0_RN(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_R0_RM(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_DISP_GBR(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RN_PC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_RM_PC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_R0_GBR(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_DISP_PC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_DISP_PC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_DISP_RN(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_DISP_RM(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_IMM_RN_RM(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_AT_DISP_PC_ALIGN(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_RN_PC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_RM_PC(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_SR(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_GBR(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_VBR(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_MACH(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_MACL(const struct SH_INSTRUCTION*, char*, UNK);
    UNK CATH_OPERAND_TYPE_PR(const struct SH_INSTRUCTION*, char*, UNK);

#endif
#endif
