// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS
//
// MORE SPECIFICALLY, THIS FILE FOCUSSES ON THE INLINED HELPER FUNCTIONS

#ifndef CATH_INSTR_HELPER_HPP
#define CATH_INSTR_HELPER_HPP

#pragma once

// NESTED INCLUDES

#include "instructions/instruction.hpp"

namespace catherine
{
    class CATH_INSTRUCTION_HELPER : public CATH_INSTRUCTION
    {

    };
}


#endif