// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS
//
// SPECIFICALLY, FOCUSSING ON THE INHERITANCE METHODS OF CREATING AN INSTRUCTION BASE
// TYPE FOR THE CURRENT WORD AND ADDRESS

#ifndef CATH_INSTR_SH2_BASE_HPP
#define CATH_INSTR_SH2_BASE_HPP

#pragma once 

// NESTED INCLUDES

#include "instructions/instruction.hpp"

namespace catherine
{    
    class CATH_INSTRUCTION_SH2 : public CATH_INSTRUCTION
    {
        public:
            CATH_INSTRUCTION_SH2(U16 WORD, U32 ADDRESS);
            virtual ~CATH_INSTRUCTION_SH2() = default;
    };

    // HELPER FUNCTIONS MOSTLY TO DO WITH ACCESSING SPECIFIC
    // INSTRUCTION TYPES - SOME NECESSARY FOR THE RECOMPILED BLOCKS

    inline bool CATH_INSTR_IS_RTS(const CATH_INSTRUCTION& INSTR)
    { 
        return INSTR.CATH_GET_UNIQUE_ID() == catherine::CATH_INSTR_ID_CXX::CATH_INSTR_ID_RTS;
    }
}

#endif
