// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS AND THEIR RESPECTIVE CATEGORY

#ifndef CATH_INSTR_CATEGORY_H
#define CATH_INSTR_CATEGORY_H

typedef enum
{
    CATH_INSTRCAT_SH2,
    CATH_INSTRCAT_DSP,
    
} CATH_INSTR_CAT;

#endif