// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

#ifndef CATH_INSTR_ENUM_H
#define CATH_INSTR_ENUM_H

// SEE: https://antime.kapsi.fi/sega/files/h12p0.pdf#page=10

typedef enum CATH_INSTR_ID
{
    CATH_INSTR_ID_INVALID,
    CATH_INSTR_ID_ADD,
    CATH_INSTR_ID_ADDC,
    CATH_INSTR_ID_ADDV,
    CATH_INSTR_ID_ADDI,
    CATH_INSTR_ID_BF,
    CATH_INSTR_ID_BFS,
    CATH_INSTR_ID_BRA,
    CATH_INSTR_ID_BRAF,
    CATH_INSTR_ID_BSR,
    CATH_INSTR_ID_BSRF,
    CATH_INSTR_ID_BT,
    CATH_INSTR_ID_BTS,
    CATH_INSTR_ID_CLRMAC,
    CATH_INSTR_ID_CLRT,
    CATH_INSTR_ID_CMP,
    CATH_INSTR_ID_DIV0S,
    CATH_INSTR_ID_DIV0U,
    CATH_INSTR_ID_DIV1,
    CATH_INSTR_ID_DMULS,
    CATH_INSTR_ID_DMULU,
    CATH_INSTR_ID_DT,
    CATH_INSTR_ID_EXTS,
    CATH_INSTR_ID_EXTU,
    CATH_INSTR_ID_JMP,
    CATH_INSTR_ID_JSR,
    CATH_INSTR_ID_LDC,
    CATH_INSTR_ID_LDS,
    CATH_INSTR_ID_MACW,
    CATH_INSTR_ID_MACL,
    CATH_INSTR_ID_MOV,                  // MOV RM, RN
    CATH_INSTR_ID_MOVL,                 // MOV @RM, RN
    CATH_INSTR_ID_MOVL0,                // MOV @(RM), RN
    CATH_INSTR_ID_MOVL4,                // MOV @(DISP, RM), R0
    CATH_INSTR_ID_MOVLG,                // MOV @(DISP, GBR), R0
    CATH_INSTR_ID_MOVM,                 // MOV RM, @-RN
    CATH_INSTR_ID_MOVP,                 // MOV @RM+, RN
    CATH_INSTR_ID_MOVS,                 // MOV RM, @RN
    CATH_INSTR_ID_MOVS0,                // MOV RM, @R0, RN)
    CATH_INSTR_ID_MOVS4,                // MOV R0, @(DISP, RN)
    CATH_INSTR_ID_MOVSG,                // MOV R0, @DISP, GBR)
    CATH_INSTR_ID_MOVI,                 // MOV #imm, RN
    CATH_INSTR_ID_MOVIPC,               // MOV @(DISP, PC), RN
    CATH_INSTR_ID_MOVA,                 // MOVA @(DISP, PC), R0
    CATH_INSTR_ID_MOVT,                 // MOVT RN 
};

#endif