// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

#ifndef CATH_INSTR_ENUM_H
#define CATH_INSTR_ENUM_H

// THE FOLLOWING PROVIDES TWO ENUMS WITH DIFFERING PURPOSES
// ONE FOCUSSES ON THE ACTUAL OPCODE/INSTRUCTION ID
// THE OTHER FOCUSSESS ON THE TYPES OF INSTRUCTION

// SEE: https://antime.kapsi.fi/sega/files/h12p0.pdf#page=10

typedef enum CATH_INSTR_ID
{
    CATH_INSTR_ID_INVALID,
    CATH_INSTR_ID_ADD,
    CATH_INSTR_ID_ADDC,
    CATH_INSTR_ID_ADDV,
    CATH_INSTR_ID_ADDI,
    CATH_INSTR_ID_BF,
    CATH_INSTR_ID_BFS,
    CATH_INSTR_ID_BRA,
    CATH_INSTR_ID_BRAF,
    CATH_INSTR_ID_BSR,
    CATH_INSTR_ID_BSRF,
    CATH_INSTR_ID_BT,
    CATH_INSTR_ID_BTS,
    CATH_INSTR_ID_CLRMAC,
    CATH_INSTR_ID_CLRT,
    CATH_INSTR_ID_CMP,
    CATH_INSTR_ID_DIV0S,
    CATH_INSTR_ID_DIV0U,
    CATH_INSTR_ID_DIV1,
    CATH_INSTR_ID_DMULS,
    CATH_INSTR_ID_DMULU,
    CATH_INSTR_ID_DT,
    CATH_INSTR_ID_EXTS,
    CATH_INSTR_ID_EXTU,
    CATH_INSTR_ID_JMP,
    CATH_INSTR_ID_JSR,
    CATH_INSTR_ID_LDC,
    CATH_INSTR_ID_LDS,
    CATH_INSTR_ID_MACW,
    CATH_INSTR_ID_MACL,
    CATH_INSTR_ID_MOV,                  // MOV RM, RN
    CATH_INSTR_ID_MOVL,                 // MOV @RM, RN
    CATH_INSTR_ID_MOVL0,                // MOV @(RM), RN
    CATH_INSTR_ID_MOVL4,                // MOV @(DISP, RM), R0
    CATH_INSTR_ID_MOVLG,                // MOV @(DISP, GBR), R0
    CATH_INSTR_ID_MOVM,                 // MOV RM, @-RN
    CATH_INSTR_ID_MOVP,                 // MOV @RM+, RN
    CATH_INSTR_ID_MOVS,                 // MOV RM, @RN
    CATH_INSTR_ID_MOVS0,                // MOV RM, @R0, RN)
    CATH_INSTR_ID_MOVS4,                // MOV R0, @(DISP, RN)
    CATH_INSTR_ID_MOVSG,                // MOV R0, @DISP, GBR)
    CATH_INSTR_ID_MOVI,                 // MOV #imm, RN
    CATH_INSTR_ID_MOVIPC,               // MOV @(DISP, PC), RN
    CATH_INSTR_ID_MOVA,                 // MOVA @(DISP, PC), R0
    CATH_INSTR_ID_MOVT,                 // MOVT RN 
    CATH_INSTR_ID_MUL,
    CATH_INSTR_ID_MULU,
    CATH_INSTR_ID_MULS,
    CATH_INSTR_ID_NEG,
    CATH_INSTR_ID_NEGC,
    CATH_INSTR_ID_NOP,
    CATH_INSTR_ID_NOT,
    CATH_INSTR_ID_OR,
    CATH_INSTR_ID_ROTCL,
    CATH_INSTR_ID_ROTCR,
    CATH_INSTR_ID_ROTL,
    CATH_INSTR_ID_ROTR,
    CATH_INSTR_ID_RTE,
    CATH_INSTR_ID_RTS,
    CATH_INSTR_ID_SETT,
    CATH_INSTR_ID_SHAL,
    CATH_INSTR_ID_SHAR,
    CATH_INSTR_ID_SHLL,
    CATH_INSTR_ID_SHLLN,
    CATH_INSTR_ID_SHLR,
    CATH_INSTR_ID_SHLRN,
    CATH_INSTR_ID_SLEEP,
    CATH_INSTR_ID_STC,
    CATH_INSTR_ID_STS,
    CATH_INSTR_ID_SUB,
    CATH_INSTR_ID_SUBC,
    CATH_INSTR_ID_SUBV,
    CATH_INSTR_ID_SWAP,
    CATH_INSTR_ID_TAS,
    CATH_INSTR_ID_TRAPA,
    CATH_INSTR_ID_TST,
    CATH_INSTR_ID_XOR,
    CATH_INSTR_ID_XTRCT,
    CATH_INSTR_ID_ALL_MAX
    
} CATH_INSTR_ID; 

typedef enum CATH_INSTR_ID_TYPE
{
    CATH_INSTR_ID_TYPE_INVALID = 0,
    CATH_INSTR_ID_TYPE_NORMAL,
    CATH_INSTR_ID_TYPE_SPECIAL,
    CATH_INSTR_ID_TYPE_ALU,
    CATH_INSTR_ID_TYPE_SHIFT,
    CATH_INSTR_ID_TYPE_LOAD,
    CATH_INSTR_ID_TYPE_STORE,
    CATH_INSTR_ID_TYPE_BRANCH,
    CATH_INSTR_ID_TYPE_BRANCH_COND,
    CATH_INSTR_ID_TYPE_JUMP,
    CATH_INSTR_ID_TYPE_RTS,
    CATH_INSTR_ID_TYPE_MUL,
    CATH_INSTR_ID_TYPE_DIV,
    CATH_INSTR_ID_TYPE_MAC,

    CATH_INSTR_ID_TYPE_SYS,
    CATH_INSTR_ID_TYPE_PRIV,
    CATH_INSTR_ID_TYPE_STATUS,
    CATH_INSTR_ID_TYPE_GBR_ACCESS,
    CATH_INSTR_ID_TYPE_PC_REL,

    CATH_INSTR_ID_TYPE_TEST,
    CATH_INSTR_ID_TYPE_COMP,

    CATH_INSTR_ID_TYPE_CACHE,
    CATH_INSTR_ID_TYPE_MAX

} CATH_INSTR_ID_TYPE;

#endif
