// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE REGISTERS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE REGISTERS

#ifndef CATH_REGISTER_NAMES_H
#define CATH_REGISTER_NAMES_H

typedef enum CATH_GPR
{
    SH2_REG_R0 = 0,
    SH2_REG_R1,
    SH2_REG_R2,
    SH2_REG_R3,
    SH2_REG_R4,
    SH2_REG_R5,
    SH2_REG_R6,
    SH2_REG_R7,
    SH2_REG_R8,
    SH2_REG_R9,
    SH2_REG_R10,
    SH2_REG_R11,
    SH2_REG_R12,
    SH2_REG_R13,
    SH2_REG_R14,
    SH2_REG_R15,
    SH2_REG_MAX

} CATH_GPR;

typedef enum CATH_CTRL
{
    SH2_REG_SR = 0,
    SH2_REG_GBR,
    SH2_REG_VBR,
    SH2_REG_CTRL_MAX

} CATH_CTRL;

typedef enum CATH_SYS
{
    SH2_REG_MACH = 0,
    SH2_REG_MACL,
    SH2_REG_PR,
    SH2_REG_SYS_MAX

} CATH_SYS;

#endif