// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE REGISTERS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE DSP REGISTERS

#ifndef CATH_DSP_REGISTER_NAMES_H
#define CATH_DSP_REGISTER_NAMES_H

typedef enum CATH_DSP_MC_REG
{
    DSP_REG_MC0 = 0,
    DSP_REG_MC1,
    DSP_REG_MC2,
    DSP_REG_MC3,
    DSP_REG_MC_MAX

} CATH_DSP_MC_REG;

typedef enum CATH_DSP_RA_REG
{
    DSP_REG_RA0 = 0,
    DSP_REG_RA1,
    DSP_REG_RA2,
    DSP_REG_RA3,
    DSP_REG_RA_MAX
     
} CATH_DSP_RA_REG;

typedef enum CATH_DSP_CT_REG
{
    DSP_REG_CT0 = 0,
    DSP_REG_CT1,
    DSP_REG_CT2,
    DSP_REG_CT3,
    DSP_REG_CT_MAX

} CATH_DSP_CT_REG;

typedef enum CATH_DSP_SPECIAL_REG
{
    DSP_REG_ACC = 0,
    DSP_REG_ALU,
    DSP_REG_MUL,
    DSP_REG_PC,
    DSP_REG_TOP,
    DSP_REG_LOP,
    DSP_REG_DMA,
    DSP_REG_ALL,
    DSP_REG_SPECIAL_MAX 
    
} CATH_DSP_SPECIAL_REG;

#endif
