// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

// NESTED INCLUDES

#include "instructions/instruction.h"

// INITIALISE THE BASIS FOR THE PROVIDED INSTRUCTION
// ACCESS THE WORD ENCOMPASSING THE INSTRUCTION AND IT'S RESPECTIVE ADDRESS
void CATH_INSTRUCTION_INIT(SH_INSTRUCTION* INSTR, U16 WORD, U32 ADDRESS)
{
    INSTR->WORD = WORD;
    INSTR->BITS = 0;

    INSTR->INSTR_ID = CATH_INSTR_ID_INVALID;
    INSTR->DESCRIPTOR = &INSTR_DESCRIPTORS[INSTR->INSTR_ID];
    INSTR->ID_TYPE = CATH_INSTR_ID_TYPE_INVALID;

    INSTR->PC = ADDRESS;
    INSTR->CATEGORY = CATH_INSTRCAT_SH2;

    INSTR->FLAGS = 0;
}