// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

// NESTED INCLUDES

#include "enums/instr_enum.h"

// SYSTEM INCLUDES

#include <assert.h>

// DETERMINE THE VALIDITY OF EACH OF THE INSTRUCTION NAMES FROM THE RESPECTIVE ENUM
static const char* CATH_GET_OPCODE_NAME(CATH_INSTR_ID INSTR_ID)
{
    const char* NAME; 
    assert(INSTR_ID >= CATH_INSTR_ID_INVALID && INSTR_ID < CATH_INSTR_ID_ALL_MAX);
}