// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

// NESTED INCLUDES

#include "instructions/instruction.h"

// INITIALISE THE BASIS FOR THE PROVIDED INSTRUCTION
// ACCESS THE WORD ENCOMPASSING THE INSTRUCTION AND IT'S RESPECTIVE ADDRESS
void CATH_INSTRUCTION_INIT(SH_INSTRUCTION* INSTR, U16 WORD, U32 ADDRESS)
{
    INSTR->WORD = WORD;
    INSTR->BITS = 0;

    INSTR->INSTR_ID = CATH_INSTR_ID_INVALID;
    INSTR->DESCRIPTOR = &INSTR_DESCRIPTORS[INSTR->INSTR_ID];
    INSTR->ID_TYPE = CATH_INSTR_ID_TYPE_INVALID;

    INSTR->PC = ADDRESS;
    INSTR->CATEGORY = CATH_INSTRCAT_SH2;

    INSTR->FLAGS = 0;
}

// GET THE SIGN EXTENDED IMMEDIATE VALUE BASED OFF OF 
// THE CORRESPONDING DESCRIPTOR VALUE
S32 CATH_INSTRUCTION_GET_IMM(const SH_INSTRUCTION* INSTR)
{
    U8 IMM = SH2_INSTR_GET_IMM8(INSTR);

    // CHECK IF THE CURRENT INSTRUCTION USES
    // AN UNSIGNED IDENTIFIER
    if(INSTR->DESCRIPTOR && INSTR->DESCRIPTOR->IS_UNSIGNED) return (S32)IMM;

    // SIGN EXTEND TO 32 BIT AS EVENTUAL RET 
    return (S32)(S8)IMM;
}

// GET THE CURRENT DISPLACEMENT VALUES ASSOCIATED WITH AN INSTRUCTION
S32 CATH_INSTRUCTION_GET_DISP(const SH_INSTRUCTION* INSTR)
{
    // DETERMINE THE SIZE OF THE DISPLACEMENT BASED ON INSTRUCTION
    // RANGING FROM 4 TO 12 BIT PER 16 BIT WORD
    switch(INSTR->INSTR_ID)
    {
        case CATH_INSTR_ID_MOVBL4:
        case CATH_INSTR_ID_MOVWL4:
        case CATH_INSTR_ID_MOVLL4:
        case CATH_INSTR_ID_MOVBS4:
        case CATH_INSTR_ID_MOVWS4:
        case CATH_INSTR_ID_MOVLS4:
        {
            U8 DISP_4 = SH2_INSTR_GET_DISP4(INSTR);

            // SCALE DISPLACEMENT VALUE BASED ON ACCESS SIZE
            if(INSTR->INSTR_ID == CATH_INSTR_ID_MOVBL4 ||
                INSTR->INSTR_ID == CATH_INSTR_ID_MOVBS4)
                return DISP_4;

            else if(INSTR->INSTR_ID == CATH_INSTR_ID_MOVWL4 ||
                    INSTR->INSTR_ID == CATH_INSTR_ID_MOVWS4)
                return DISP_4 * 2;
            else
                return DISP_4 * 4;
        }
    }
}
