// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS

// NESTED INCLUDES

#include "instructions/instruction.h"
#include "tables/tables.h"

// ACCESS THE CURRENT BUFFER SIZE FOR EACH OPERAND
// ASSUME SUCH ON THE BASIS OF THE PROVIDED CALLBACK TO LAISE WITH 
// THE DECLARATIONS OF EACH OPERAND TYPE
UNK CATH_OPERAND_TYPE_GET_BUFFER_SIZE(SH_OPERAND_TYPE TYPE, const SH_INSTRUCTION* INSTR)
{
    // ASSIGN THE CALLBACK TO EACH RESPECTIVE TYPE
    SH2_OPERAND_CALLBACK CB;
    CB = INSTR_CALLBACKS[TYPE];

    return CB(INSTR, NULL, 0);
}

// SIMILAR BUT THIS TIME, ACCESS THE DESTINATION FROM THE CALLBACK
UNK CATH_OPERAND_TYPE_DISASM(SH_OPERAND_TYPE TYPE, const SH_INSTRUCTION* INSTR, char* DEST, UNK MAX_LEN)
{
    SH2_OPERAND_CALLBACK CB;
    CB = INSTR_CALLBACKS[TYPE];

    return CB(INSTR, DEST, MAX_LEN);
}

// DETERMINES ALL OF THE CONURRENT OPERANDS AND APPLIES
// THEM TO THE BUFFER
UNK CATH_INSTRUCTION_DISASM_OPERAND(const SH_INSTRUCTION* INSTR, char* DEST, UNK BUFFER_SIZE)
{
    UNK TOTAL_SIZE = 0;

    for(UNK INDEX = 0; INDEX < CATH_ARRAY(INSTR->DESCRIPTOR->OPERAND_TYPE) && 
        INSTR->DESCRIPTOR->OPERAND_TYPE[INDEX] != OPERAND_NONE; INDEX++)
    {
       // ADD SEPARATOR PADDING BETWEEN OPERANDS
       // NOW WITH THE DETERMINISTIC BEHAVIOUR SUCH THAT
       // THE BUFFER SIZE DOESN'T OVERFLOW

       if(INDEX > 0 && TOTAL_SIZE > 0)
       {
            // 19/06/26
            // FREAKY FIX DESIGNED SUCH THAT THE BUFFER ONLY
            // EVER STOPS TRUNCATING ONCE THE TOTAL SIZE 
            // HAS EVER EXCEEDED IN CONJUNCTION
            //
            // I AM NEVER TOUCHING THIS AGAIN!!
            if(DEST != NULL && TOTAL_SIZE + 2 >= BUFFER_SIZE) break;
            
            if(DEST != NULL)
            {
                DEST[TOTAL_SIZE] = ',';
                DEST[TOTAL_SIZE + 1] = ' ';
            }

            TOTAL_SIZE += 2;
       }

       // ACCOUNT FOR ANY AND ALL REMAINING SPACE WITHIN THE BUFFER ITSELF
       // THIS WILL HELP WHEN REFERENCING THE OPERAND SIZE
       //
       // 19/06/26
       // ORIGINALLY, THE BUFFER WOULD UNDERFLOLW AS A RESULT
       // OF WHEN BUFFER SIZE ENDS UP B BEING ZEROED
       // 
       // THE FIX BEING TO ONLY SUBTRACT WHEN THERE IS ROOM LEFT 
       // IN THE BUFFER FOR AT LEAST ONE BYTE PLUS THE NULL TERM
       UNK REMAINING_SIZE = (BUFFER_SIZE > TOTAL_SIZE + 1) ? (BUFFER_SIZE - TOTAL_SIZE - 1) : 0;

       // AUTOMATICALLY ASSIGN THE SIZE BASED ON WHAT IS BEING DISASSEMBLED
       //
       // 19/06/26
       // FIXED TO PROPERLY GUARD AGINST THE NULL TERM
       // TO PREVENT THE AFOREMENTIONED UNDERFLOW
       UNK OPERAND_SIZE = CATH_OPERAND_TYPE_DISASM(
                            INSTR->DESCRIPTOR->OPERAND_TYPE[INDEX], 
                            INSTR, 
                            (DEST != NULL) ? (DEST + TOTAL_SIZE) : NULL,
                            REMAINING_SIZE);

        // WITH ALL OF THESE ADJUSTMENTS, WE CAN ONLY EVER ASSUME
        // THAT THE REMAINING SIZE BYTES CLAMP PROPERLY SUCH
        // THAT TOTAL SIZE NEVER OUTGROWS THE BUDGET OF THE BUFFER
        // THAT WAS GIVEN DYNAMICALLY PER OPERAND

        if(DEST != NULL && OPERAND_SIZE > REMAINING_SIZE)
        {
            OPERAND_SIZE = REMAINING_SIZE;
        }

       TOTAL_SIZE += OPERAND_SIZE;
    }

    return TOTAL_SIZE;
}
