// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE OPERANDS
//
// MORE SPECIFICALLY, THIS FILE ACCESSES ALL OF THE OPERAND FUNCTION CALLS
// AND TYPES, ACCESSES THE CURRENT STRING LITERAL OF THE OPERAND
// AND RETURNS ACCORDINGLY

// NESTED INCLUDES

#include "instructions/operands.h"
#include "instructions/instruction.h"
#include "instructions/register.h"
#include "tables/tables.h"

UNK CATH_OPERAND_TYPE_NONE(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    (void)BUFFER;
    (void)SIZE;
    return 0;
}

UNK CATH_OPERAND_TYPE_RM(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RM = SH2_INSTR_GET_RM(INSTR);
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_GPRNAME(RM));
}

UNK CATH_OPERAND_TYPE_RN(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_GPRNAME(RN));
}

UNK CATH_OPERAND_TYPE_R0(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    CATH_SPRINTF(BUFFER, SIZE, "%s", "R0");
    return SIZE;
}

UNK CATH_OPERAND_TYPE_IMM(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    S32 IMM = CATH_INSTRUCTION_GET_IMM(INSTR);
    return snprintf(BUFFER, SIZE, "#0x%X", (U32)IMM);
}

UNK CATH_OPERAND_TYPE_AT_RN(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    return snprintf(BUFFER, SIZE, "@%s", CATH_REGISTER_GET_GPRNAME(RN));
}

UNK CATH_OPERAND_TYPE_AT_RM(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RM = SH2_INSTR_GET_RM(INSTR);
    return snprintf(BUFFER, SIZE, "@%s", CATH_REGISTER_GET_GPRNAME(RM));
}

UNK CATH_OPERAND_TYPE_AT_RM_POST_INC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RM = SH2_INSTR_GET_RM(INSTR);
    return snprintf(BUFFER, SIZE, "@%s+", CATH_REGISTER_GET_GPRNAME(RM));
}

UNK CATH_OPERAND_TYPE_AT_RN_PRE_DEC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    return snprintf(BUFFER, SIZE, "@-%s", CATH_REGISTER_GET_GPRNAME(RN));
}
UNK CATH_OPERAND_TYPE_AT_RN_POST_INC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    return snprintf(BUFFER, SIZE, "@%s+", CATH_REGISTER_GET_GPRNAME(RN));
}

UNK CATH_OPERAND_TYPE_AT_R0_RN(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    return snprintf(BUFFER, SIZE, "@(R0, %s)", CATH_REGISTER_GET_GPRNAME(RN));
}

UNK CATH_OPERAND_TYPE_AT_R0_RM(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RM = SH2_INSTR_GET_RM(INSTR);
    return snprintf(BUFFER, SIZE, "@(R0, %s", CATH_REGISTER_GET_GPRNAME(RM));
}

UNK CATH_OPERAND_TYPE_AT_DISP_GBR(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 DISP = SH2_INSTR_GET_GBR_DISP(INSTR);
    return snprintf(BUFFER, SIZE, "@(0x%X, GBR)", DISP);
}

UNK CATH_OPERAND_TYPE_AT_RN_PC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    return snprintf(BUFFER, SIZE, "@(%s, PC)", CATH_REGISTER_GET_GPRNAME(RN));
}

UNK CATH_OPERAND_TYPE_AT_R0_GBR(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "@(R0, GBR)");
}

UNK CATH_OPERAND_TYPE_AT_DISP_PC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U32 ADDRESS = CATH_GET_PC(INSTR);
    return snprintf(BUFFER, SIZE, "@(#0x%X)", ADDRESS);
}

UNK CATH_OPERAND_TYPE_DISP_PC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U32 TARGET = CATH_GET_BRANCH_OFFSET(INSTR);
    return snprintf(BUFFER, SIZE, "0x%08X", TARGET);
}

UNK CATH_OPERAND_TYPE_AT_DISP_RN(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    U8 DISP = SH2_INSTR_GET_DISP4(INSTR);

    U32 SCALE = CATH_DISP_SCALE[INSTR->INSTR_ID];
    U32 SCALED_DISP = DISP * SCALE;
    return snprintf(BUFFER, SIZE, "@(0x%X, %s)", SCALED_DISP, CATH_REGISTER_GET_GPRNAME(RN));
}

UNK CATH_OPERAND_TYPE_AT_DISP_RM(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RM = SH2_INSTR_GET_RM(INSTR);
    U8 DISP = SH2_INSTR_GET_DISP4(INSTR);

    U32 SCALE = CATH_DISP_SCALE[INSTR->INSTR_ID];
    U32 SCALED_DISP = DISP * SCALE;
    return snprintf(BUFFER, SIZE, "@(0x%X, %s)", SCALED_DISP, CATH_REGISTER_GET_GPRNAME(RM));
}

UNK CATH_OPERAND_TYPE_AT_IMM_RN_RM(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    U8 RM = SH2_INSTR_GET_RM(INSTR);
    S32 IMM = CATH_INSTRUCTION_GET_IMM(INSTR);

    return snprintf(BUFFER, SIZE, "@(#0x%X, %s, %s)",
                    (U32)IMM,
                    CATH_REGISTER_GET_GPRNAME(RN),
                    CATH_REGISTER_GET_GPRNAME(RM));
}

UNK CATH_OPERAND_TYPE_RN_PC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RN = SH2_INSTR_GET_RN(INSTR);
    return snprintf(BUFFER, SIZE, "%s+PC", CATH_REGISTER_GET_GPRNAME(RN));
}

UNK CATH_OPERAND_TYPE_RM_PC(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 RM = SH2_INSTR_GET_RM(INSTR);
    return snprintf(BUFFER, SIZE, "%s+PC", CATH_REGISTER_GET_GPRNAME(RM));
}

UNK CATH_OPERAND_TYPE_AT_DISP_PC_ALIGN(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    // LOAD RELATIVE PC ADDRESS BASED ON ALIGNED BOUNDS
    U32 ADDRESS = CATH_GET_PC(INSTR);
    U32 ALIGNED = (ADDRESS + 4) & ~3;

    return snprintf(BUFFER, SIZE, "@(#0x%X, PC)", ALIGNED);
}

UNK CATH_OPERAND_TYPE_SR(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "SR");
}

UNK CATH_OPERAND_TYPE_GBR(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "GBR");
}

UNK CATH_OPERAND_TYPE_VBR(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "VBR");
}

UNK CATH_OPERAND_TYPE_MACH(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "MACH");
}

UNK CATH_OPERAND_TYPE_MACL(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "MACL");
}

UNK CATH_OPERAND_TYPE_PR(const SH_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "PR");
}
