// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE REGISTERS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE REGISTERS

// NESTED INCLUDES

#include "instructions/register.h"

// SYSTEM INCLUDES  

#include <assert.h>

CATH_CONFIG CC = 
{
    .REG_ALIAS = CATH_REG_UPPER,
    .USE_ALIAS = false,
};

// ACCESS ALL OF THE CONCURRENT REGISTER NAMES FROM THE ENUM
const char* CATH_REGISTER_GET_GPRNAME(U8 VALUE)
{
    assert(VALUE < SH2_REG_MAX);
    return CATH_GPR_NAMES[VALUE][CC.REG_ALIAS];
}

const char* CATH_REGISTER_GET_CTRLNAME(U8 VALUE)
{
    assert(VALUE < SH2_REG_CTRL_MAX);;
    return CATH_CTRL_NAMES[VALUE];
}

const char* CATH_REGISTER_GET_SYSNAME(U8 VALUE)
{
    assert(VALUE < SH2_REG_SYS_MAX);;
    return CATH_SYS_NAMES[VALUE];
}
