// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS OF THE SCU DSP 

// NESTED INCLUDES

#include "tables/tables.h"
#include "instructions/instructionDSP.h"

// INITIALISE THE BASIS FOR THE PROVIDED INSTRUCTION
// ACCESS THE WORD ENCOMPASSING THE INSTRUCTION AND IT'S RESPECTIVE ADDRESS
void CATH_DSP_INSTRUCTION_INIT(SH_DSP_INSTRUCTION* INSTR, U32 WORD, U32 ADDRESS)
{
    INSTR->WORD = WORD;
    INSTR->FLAGS = 0;
    INSTR->DESCRIPTOR = &DSP_DESCRIPTORS[CATH_INSTR_ID_DSP_INVALID];
    INSTR->INSTR_ID = CATH_INSTR_ID_DSP_INVALID;
    INSTR->CATEGORY = CATH_INSTRCAT_DSP;
    INSTR->PC = ADDRESS;
    INSTR->IS_PARALLEL = false;
    INSTR->D_SLOT.IS_ACTIVE = false;
    INSTR->D_SLOT.MNEMONIC = NULL;
    INSTR->D_SLOT.DEST_NAME = NULL;
    INSTR->D_SLOT.SRC_NAME = NULL;
    INSTR->D_SLOT.SOURCE = DSP_OPERAND_NONE;
}

// DETERMINE THE SIZE OF THE CURRENT INSTRUCTION IN THE OUTPUT BUFFER
// WITHOUT WRITING TO IT ACCORDINGLY
//
// MIRRORS THE DESIGN PATTERNS OF CATH_INSTRUCTION_GET_SIZE 
// USED BY CALLERS THAT NEED TO ALLOCATE BEFORE WRITING
UNK CATH_DSP_INSTRUCTION_GET_SIZE(const SH_DSP_INSTRUCTION* INSTR)
{
    UNK TOTAL_SIZE = 0;
    TOTAL_SIZE += strlen(CATH_GET_DSP_OPCODE_NAME(INSTR->INSTR_ID));

    // ASSUME THAT A NOP HAVE NO OPERAND FIELD AND RETURN WITH
    // A GRACEFUL FALLBACK
    if(INSTR->DESCRIPTOR->IS_NOP || INSTR->DESCRIPTOR->IS_END) return TOTAL_SIZE;

    TOTAL_SIZE += 1;
    TOTAL_SIZE += CATH_DSP_INSTRUCTION_DISASM_OPERAND(INSTR, NULL);

    return TOTAL_SIZE;
}
