// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY ENCOMPASSING THE LOOKUP TABLE
// FOR DSP DECODING
//
// SUCH IMPLEMENTATION WAS THE ONLY WAY I SOUGHT TO IMPLEMENT AN EASE OF USE MEANS OF LOOKING
// UP CORRESPONDENCES AGAINST THEIR ENUM VALUE AND DESCRIPTOR IDENTIFIER

// NESTED INCLUDES

#define CATH_USE_BUS_DECODE_TABLE

#include "instructions/instructionDSP.h"
#include "instructions/registerDSP.h"

const SH_DSP_ENTRY CATH_DSP_ENTRY_TABLE[] =
{
    { .MASK = 0xFF000000, .PATTERN = 0xD1000000, .ID = CATH_INSTR_ID_DSP_JMP },
    { .MASK = 0xFF000000, .PATTERN = 0xD0000000, .ID = CATH_INSTR_ID_DSP_JMP },

    { .MASK = 0xFF000000, .PATTERN = 0xE0000000, .ID = CATH_INSTR_ID_DSP_AD2  },
    { .MASK = 0xFF000000, .PATTERN = 0xE1000000, .ID = CATH_INSTR_ID_DSP_ADD  },
    { .MASK = 0xFF000000, .PATTERN = 0xE2000000, .ID = CATH_INSTR_ID_DSP_SUB  },
    { .MASK = 0xFF000000, .PATTERN = 0xE4000000, .ID = CATH_INSTR_ID_DSP_AND  },
    { .MASK = 0xFF000000, .PATTERN = 0xE5000000, .ID = CATH_INSTR_ID_DSP_OR   },
    { .MASK = 0xFF000000, .PATTERN = 0xE6000000, .ID = CATH_INSTR_ID_DSP_XOR  },
    { .MASK = 0xFF000000, .PATTERN = 0xE7000000, .ID = CATH_INSTR_ID_DSP_NOT  },
    { .MASK = 0xFF000000, .PATTERN = 0xE8000000, .ID = CATH_INSTR_ID_DSP_SL   },
    { .MASK = 0xFF000000, .PATTERN = 0xE9000000, .ID = CATH_INSTR_ID_DSP_SR   },
    { .MASK = 0xFF000000, .PATTERN = 0xEA000000, .ID = CATH_INSTR_ID_DSP_RL   },
    { .MASK = 0xFF000000, .PATTERN = 0xEB000000, .ID = CATH_INSTR_ID_DSP_RR   },
    { .MASK = 0xFF000000, .PATTERN = 0xEC000000, .ID = CATH_INSTR_ID_DSP_CLR  },

    { .MASK = 0xFC000000, .PATTERN = 0x00000000, .ID = CATH_INSTR_ID_DSP_NOP  },
    { .MASK = 0xFC000000, .PATTERN = 0x04000000, .ID = CATH_INSTR_ID_DSP_END  },
    { .MASK = 0xFC000000, .PATTERN = 0x08000000, .ID = CATH_INSTR_ID_DSP_ENDI },
    { .MASK = 0xFC000000, .PATTERN = 0x40000000, .ID = CATH_INSTR_ID_DSP_LOOP },
    { .MASK = 0xFC000000, .PATTERN = 0x44000000, .ID = CATH_INSTR_ID_DSP_BTM  },
    { .MASK = 0xFC000000, .PATTERN = 0x48000000, .ID = CATH_INSTR_ID_DSP_LPS  },
    { .MASK = 0xFC000000, .PATTERN = 0x60000000, .ID = CATH_INSTR_ID_DSP_BF   },
    { .MASK = 0xFC000000, .PATTERN = 0xC0000000, .ID = CATH_INSTR_ID_DSP_MOV  },
    { .MASK = 0xFC000000, .PATTERN = 0xC4000000, .ID = CATH_INSTR_ID_DSP_DMA  },
    { .MASK = 0xFC000000, .PATTERN = 0xE4000000, .ID = CATH_INSTR_ID_DSP_MUL  },

    { .MASK = 0xC0000000, .PATTERN = 0x80000000, .ID = CATH_INSTR_ID_DSP_MVI  },

    { .MASK = 0, .PATTERN = 0, .ID = CATH_INSTR_ID_DSP_INVALID },
};

const UNK CATH_DSP_ENTRY_TABLE_SIZE = sizeof(CATH_DSP_ENTRY_TABLE) / sizeof(CATH_DSP_ENTRY_TABLE[0]);

// POPULATES A PARALLEL SLOT FROM A BUS OPERATIONS TABLE ENTRY
// IN THIS CASE, WE WANT TO DERIVE THE SOURCE AND DEST NAMES FROM EACH FIELD
// 
// FOR EACH ENTRY, WE WANT TO DETERMNE WHAT THE CORRESPONDENCE WOULD BE
// FROM ACCESSING OF THE 8 BIT AND 16 BIT FIELD - THE LATTER OF WHICH 
// GOES DIRECTLY INTO THE BUFFER, WITH THE FORMER BEING A DERIVATIVE OF 
// THE SOURCE NAME FOR THE TABLE ENTRY 
static void CATH_DSP_DECODE_BUS_SLOT(SH_DSP_PARALLEL_SLOT* SLOT, const SH_DSP_INSTRUCTION* INSTR,
                                    const SH_DSP_D_OP_ENTRY* TABLE, U8 OPERATION,
                                    const char* const* SOURCE, const char* const* DEST)
{
       SLOT->IS_ACTIVE = false;
       SLOT->MNEMONIC = NULL;
       SLOT->DEST_NAME = NULL;
       SLOT->SRC_NAME = NULL;
       SLOT->SOURCE = DSP_OPERAND_NONE;

       for(const SH_DSP_D_OP_ENTRY* PARALLEL = TABLE; PARALLEL->OP_MASK != 0; PARALLEL++)
       {
            // IF THE CURRENT MASK DOESN'T MATCH THE PATTERN
            if((OPERATION & PARALLEL->OP_MASK) != PARALLEL->OP_PATTERN) continue;
            
            if(!PARALLEL->MNEMONIC) return;

            // ONCE WE HAVE FOUND A MATCH AND ONLY THEN
            // CAN WE BEGIN TO ASSUME THE CURRENT STATE OF THE 
            // SLOT IN QUESTION

            SLOT->IS_ACTIVE = true;
            SLOT->MNEMONIC = PARALLEL->MNEMONIC;
            SLOT->SOURCE = PARALLEL->SOURCE;
            SLOT->DEST_NAME = PARALLEL->DEST_NAME;

            // RESOLVE THE SOURCE NAME FROM THE CURRENT
            // BUS FIELD BEING ACCESSED AND ASSUME THAT FOR
            // EVERY BUS OPERATION 

            switch (PARALLEL->SOURCE)
            {
                case DSP_OPERAND_X:
                {
                    U8 SRC = (U8)(TABLE == CATH_DSP_X_OP_TABLE
                        ? SCU_DSP_GET_X_SRC(INSTR)
                        : SCU_DSP_GET_Y_SRC(INSTR));

                    if(SOURCE) SLOT->SRC_NAME = SOURCE[SRC];
                    break;
                }

                case DSP_OPERAND_Y:
                {
                    U8 SRC = (U8)SCU_DSP_GET_Y_SRC(INSTR);
                    if(SOURCE) SLOT->SRC_NAME = SOURCE[SRC];
                    break;
                }

                case DSP_OPERAND_STORE:
                {
                    U8 SRC = (U8)SCU_DSP_GET_D_SRC(INSTR);
                    if(SOURCE) SLOT->SRC_NAME = SOURCE[SRC];
                    break;
                }

                case DSP_OPERAND_ALU:
                {
                    SLOT->SRC_NAME = CATH_DSP_SPECIAL_NAMES[DSP_REG_ALU];
                    break;
                }

                case DSP_OPERAND_MUL:
                {
                    U8 SRC = (U8)SCU_DSP_GET_D_SRC(INSTR);
                    if(SOURCE) SLOT->SRC_NAME = SOURCE[SRC];
                    break;
                }
            
                default:
                    break;
            }

            // DERIVE THE DESTINATION FOR THE D BUS FROM IT'S CORRESPONDING FIELD
            // WHY THIS IS SEPARATE FROM THE PARALLELISED SOURCE EVALUATION IS THAT
            // WE NEED TO DETERMINE IF THE SLOT IS NOT ACTIVE
            if(!PARALLEL->DEST_NAME && DEST)
            {
                U8 DEST_LOC = (U8)SCU_DSP_GET_D_DEST(INSTR);
                SLOT->DEST_NAME = DEST[DEST_LOC];

                if(!SLOT->DEST_NAME) SLOT->IS_ACTIVE = false;
            }

            return;
       }
}

// FINALLY, WE PROCESS THE ENTRY AND AND DETERMINE IF
// THERE IS A CORRESPONDING MATCH

void CATH_DSP_INSTRUCTION_PROCESS(SH_DSP_INSTRUCTION* INSTR)
{
    // NO VALID INSTRUCTION?
    if(!INSTR) goto PROCESS_NONE;

    // 10/05/26
    // REWORK TO INCLUDE THE PROCESSING OF PARALLEL INSTRUCTIONS
    //
    // SUCH INSTRUCTIONS LEVERAGE A COMBINATORIAL PATTERN MATCHING
    // SCHEME AS SOME INSTRUCTIONS ENCOMPASS OTHERWISE WHEN
    // ACCESSING THE D BUS - MOST COMMONLY MOV

    INSTR->IS_PARALLEL = !SCU_DSP_IS_CONTROL_FLOW(INSTR);

    if(!INSTR->IS_PARALLEL)
    {
        for(const SH_DSP_ENTRY* ENTRY = CATH_DSP_ENTRY_TABLE; ENTRY->MASK != 0; ENTRY++)
        {
            if((INSTR->WORD & ENTRY->MASK) == ENTRY->PATTERN)
            {
                INSTR->INSTR_ID = ENTRY->ID;
                INSTR->DESCRIPTOR = (ENTRY->ID < CATH_INSTR_ID_DSP_ALL_MAX)
                    ? &DSP_DESCRIPTORS[ENTRY->ID]
                    : &DSP_DESCRIPTORS[CATH_INSTR_ID_DSP_INVALID];
                return;
            }
        }

        INSTR->INSTR_ID = CATH_INSTR_ID_DSP_INVALID;
        INSTR->DESCRIPTOR = &DSP_DESCRIPTORS[CATH_INSTR_ID_DSP_INVALID];
        return;
    }

    // WHEN ACCOUNTING FOR THE PARALLELISED INSTRUCTIONS
    // WE ARE ONLY EVER CONCERNED WITH THE TOP 6 BITS OF
    // THE PROVIDED ALU FIELD

    U32 ALU_WORD = INSTR->WORD & 0xFF000000;
    INSTR->INSTR_ID = CATH_INSTR_ID_DSP_NOP;
    INSTR->DESCRIPTOR = &DSP_DESCRIPTORS[CATH_INSTR_ID_DSP_NOP];

    for(const SH_DSP_ENTRY* PARALLEL_ENTRY = CATH_DSP_ENTRY_TABLE; 
                        PARALLEL_ENTRY->MASK != 0; PARALLEL_ENTRY++)
    {
        // THE DIFFERENCE COMES IN THE FORM OF ASSINGING THE NEW
        // ALU WORD TO THE ENTRY PATTERN
        if((ALU_WORD & PARALLEL_ENTRY->MASK) == PARALLEL_ENTRY->PATTERN)
        {
            INSTR->INSTR_ID = PARALLEL_ENTRY->ID;
                INSTR->DESCRIPTOR = (PARALLEL_ENTRY->ID < CATH_INSTR_ID_DSP_ALL_MAX)
                    ? &DSP_DESCRIPTORS[PARALLEL_ENTRY->ID]
                    : &DSP_DESCRIPTORS[CATH_INSTR_ID_DSP_INVALID];
                break;
        }
    }

    // 11/05/26
    // NOW ALL OF THE CORRESPONDENCE FOR THE BUS EVALUATION AND ACCESS
    // GET PASSED THROUGH ONE LOCATION WITH DYNAMIC EVALUATION ACCORDINGLY

    CATH_DSP_DECODE_BUS_SLOT(&INSTR->X_SLOT, INSTR, 
                            CATH_DSP_X_OP_TABLE, 
                            (U8)SCU_DSP_GET_X_OP(INSTR), 
                            CATH_DSP_X_SRC_NAMES, NULL);

    CATH_DSP_DECODE_BUS_SLOT(&INSTR->Y_SLOT, INSTR, 
                            CATH_DSP_Y_OP_TABLE, 
                            (U8)SCU_DSP_GET_Y_OP(INSTR), 
                            CATH_DSP_Y_SRC_NAMES, NULL);

    CATH_DSP_DECODE_BUS_SLOT(&INSTR->D_SLOT, INSTR, 
                            CATH_DSP_D_OP_TABLE, 
                            (U8)SCU_DSP_GET_D_OP(INSTR), 
                            CATH_DSP_D_SRC_NAMES, CATH_DSP_D_DEST_NAMES);

    return;

    PROCESS_NONE:
        fprintf(stderr, "COULDN'T PROCESS INSTRUCTION: %s\n", 
            CATH_GET_DSP_OPCODE_NAME(INSTR->INSTR_ID));
}
