// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE DSP OPERANDS

// NESTED INCLUDES

#include "instructions/instructionDSP.h"
#include "instructions/operandsDSP.h"

// ACCESS THE CURRENT BUFFER SIZE FOR EACH DSP OPERAND
// FOLLOW THE SAME DESIGN PATTERN OF THE BASE OPERAND DEFINTION
UNK CATH_DSP_OPERAND_TYPE_GET_BUFFER_SIZE(SH_DSP_OPERAND_TYPE TYPE, const SH_DSP_INSTRUCTION* INSTR)
{
    // ASSIGN THE CALLBACK TO EACH RESPECTIVE TYPE
    SH_DSP_OPERAND_CALLBACK CB;
    CB = DSP_INSTR_CALLBACKS[TYPE];
    
    return CB(INSTR, NULL, 0);
}

UNK CATH_DSP_OPERAND_TYPE_DISASM(SH_DSP_OPERAND_TYPE TYPE, const struct SH_DSP_INSTRUCTION* INSTR, char* DEST)
{
    SH_DSP_OPERAND_CALLBACK CB;
    CB = DSP_INSTR_CALLBACKS[TYPE];
    
    return CB(INSTR, DEST, 64);
}

// WRITE A SINGLE STRING LITERAL TOKEN IN RELATION TO THE CURRENT BUS
// BEING ACCESSED, PRECEDED BY A SEPARATOR IF OTHER TOKENS HAVE ALREADY
// BEEN WRITTEN
// 
// NOTE: DEST MAY SOMETIMES BE NULL, IN THOSE CASES ONLY THE SIZE IS ACCUMULATED
STATIC UNK CATH_DSP_WRITE_BUS_TOKEN(char* DEST, UNK OFFSET, const char* TOKEN)
{
    UNK LENGTH = strlen(TOKEN);
    UNK WRITTEN = 0;

    // ASSUME PADDING TO BEGIN WITH AGAINST A PROVIDED BUFFER
    if(OFFSET > 0)
    {
        if(DEST)
        {
            DEST[OFFSET] = ' ';
            DEST[OFFSET + 1] = ' ';
        }

        WRITTEN += 2;
    }

    if(DEST) memcpy(DEST + OFFSET + WRITTEN, TOKEN, LENGTH);
    WRITTEN += LENGTH;

    return WRITTEN;
}

// DETERMINES ALL OF THE CONURRENT OPERANDS AND APPLIES
// THEM TO THE BUFFER
//
// A SIMILAR DESIGN PATTERN TO THE BASE DISASM OPERAND DEFINITION IS REUSED
// ALBEIT ONLY USED FOR TRACKING PARALLELISED INSTRUCTIONS 
UNK CATH_DSP_INSTRUCTION_DISASM_OPERAND(const SH_DSP_INSTRUCTION* INSTR, char* DEST)
{
    UNK TOTAL_SIZE = 0;

    // DETERMINE THE CURRENTLY USED SLOTS WITHIN THE DSP ITSELF
    // HELPS WITH DETERMINING THE CONDITIONS OF EACH RESPECTIVE "NTH_BUS"

    const SH_DSP_DESCRIPTOR* DSP_DESC = INSTR->DESCRIPTOR;
    
    // CHECK FOR SPECICAL CASES BEFORE THE DEFINITION OF 
    // BUS LOCATION - HELPS WITH UNDERSTANDING THE LENGTH
    // OF THE OPCODE 

    if(DSP_DESC->IS_END)
    {
        if(DEST)
        {
            snprintf(DEST, 64, "ENDI");
            return sizeof("ENDI") - 1;
        }
    }

    if(DSP_DESC->IS_NOP)
    {
        if(DEST)
        {
            snprintf(DEST, 64, "NOP");
            return sizeof("NOP") - 1;
        }
    }

    if(DSP_DESC->X_BUS) TOTAL_SIZE += CATH_DSP_WRITE_BUS_TOKEN(DEST, TOTAL_SIZE, "X");
    if(DSP_DESC->D_BUS) TOTAL_SIZE += CATH_DSP_WRITE_BUS_TOKEN(DEST, TOTAL_SIZE, "P");
    if(DSP_DESC->Y_BUS) TOTAL_SIZE += CATH_DSP_WRITE_BUS_TOKEN(DEST, TOTAL_SIZE, "Y");
    
    if(DEST) DEST[TOTAL_SIZE] = '\0';
    return TOTAL_SIZE;
}
