// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS OF THE SCU DSP 

// NESTED INCLUDES

#include "tables/tables.h"
#include "instructions/instructionDSP.h"

// INITIALISE THE BASIS FOR THE PROVIDED INSTRUCTION
// ACCESS THE WORD ENCOMPASSING THE INSTRUCTION AND IT'S RESPECTIVE ADDRESS
void CATH_DSP_INSTRUCTION_INIT(SH_DSP_INSTRUCTION* INSTR, U32 WORD, U32 ADDRESS)
{
    INSTR->WORD = WORD;

    INSTR->DESCRIPTOR = &INSTR_DESCRIPTORS[INSTR->INSTR_ID];
    INSTR->INSTR_ID = CATH_INSTR_ID_INVALID;

    INSTR->PC = ADDRESS;
}