// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE INSTRUCTIONS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE INSTRUCTIONS OF THE SCU DSP 

// NESTED INCLUDES

#include "tables/tables.h"
#include "instructions/instructionDSP.h"

// INITIALISE THE BASIS FOR THE PROVIDED INSTRUCTION
// ACCESS THE WORD ENCOMPASSING THE INSTRUCTION AND IT'S RESPECTIVE ADDRESS
void CATH_DSP_INSTRUCTION_INIT(SH_DSP_INSTRUCTION* INSTR, U32 WORD, U32 ADDRESS)
{
    INSTR->WORD = WORD;
    INSTR->FLAGS = 0;
    INSTR->DESCRIPTOR = &DSP_DESCRIPTORS[CATH_INSTR_ID_DSP_INVALID];
    INSTR->INSTR_ID = CATH_INSTR_ID_DSP_INVALID;
    INSTR->CATEGORY = CATH_INSTRCAT_DSP;
    INSTR->PC = ADDRESS;
    INSTR->IS_PARALLEL = false;

    // INITIALISE ALL OF THE SLOTS BASED ON THEIR CORRESPONDENCE
    // HANDLING THEM THIS WAY PREVENTS HAVING TO DO REINIT
    // ON EVERY DECODING OF THE SLOTS - WHICH CAUSED FURTHER ISSUES

    SH_DSP_PARALLEL_SLOT* SLOTS[] = 
    {
        &INSTR->X_SLOT,
        &INSTR->Y_SLOT,
        &INSTR->D_SLOT,
    };

    for(UNK INDEX = 0; INDEX < 3; INDEX++)
    {
        SLOTS[INDEX]->IS_ACTIVE = false;
        SLOTS[INDEX]->MNEMONIC = NULL;
        SLOTS[INDEX]->DEST_NAME = NULL;
        SLOTS[INDEX]->SRC_NAME = NULL;
        SLOTS[INDEX]->SOURCE = DSP_OPERAND_NONE;
    }
}

// STATICALLY AVAILABLE EMISSION FOR THE D SLOT INTO THE BUFFER
// HANDLES ALL OF THE COMBINATORIAL INSTRUCTION PATTERNS
// ON THE ASSUMPTION OF THE OPERAND TYPE BEING A STORE
static UNK CATH_DSP_EMIT_DBUS(const SH_DSP_INSTRUCTION* INSTR, char* BUFFER)
{
    if(INSTR->D_SLOT.SOURCE == DSP_OPERAND_STORE)
    {
        return snprintf(BUFFER, BUFFER ? 64 : 0,
            "%s, %s, %s",
            INSTR->D_SLOT.MNEMONIC,
            INSTR->D_SLOT.SRC_NAME,
            INSTR->D_SLOT.DEST_NAME);
    }

    else
    {
        U8 SIMM = (U8)SCU_DSP_GET_D_SIMM(INSTR);
        return snprintf(BUFFER, BUFFER ? 64 : 0,
            "%s #0x%02X, %s",
            INSTR->D_SLOT.MNEMONIC,
            SIMM,
            INSTR->D_SLOT.DEST_NAME);
    }
}

// DETERMINE THE SIZE OF THE CURRENT INSTRUCTION IN THE OUTPUT BUFFER
// WITHOUT WRITING TO IT ACCORDINGLY
//
// MIRRORS THE DESIGN PATTERNS OF CATH_INSTRUCTION_GET_SIZE 
// USED BY CALLERS THAT NEED TO ALLOCATE BEFORE WRITING
UNK CATH_DSP_INSTRUCTION_GET_SIZE(const SH_DSP_INSTRUCTION* INSTR)
{
    UNK TOTAL_SIZE = 0;
    TOTAL_SIZE += strlen(CATH_GET_DSP_OPCODE_NAME(INSTR->INSTR_ID));

    // ASSUME THAT A NOP HAVE NO OPERAND FIELD AND RETURN WITH
    // A GRACEFUL FALLBACK
    if(INSTR->DESCRIPTOR->IS_NOP || INSTR->DESCRIPTOR->IS_END)
    {
        if(INSTR->IS_PARALLEL && INSTR->D_SLOT.IS_ACTIVE)
        {
            TOTAL_SIZE += 2;
            TOTAL_SIZE += CATH_DSP_EMIT_DBUS(INSTR, NULL);
        }

        return TOTAL_SIZE;
    }

    TOTAL_SIZE += 1;
    TOTAL_SIZE += CATH_DSP_INSTRUCTION_DISASM_OPERAND(INSTR, NULL);

    if(INSTR->IS_PARALLEL && INSTR->D_SLOT.IS_ACTIVE)
    {
        TOTAL_SIZE += 2;
        TOTAL_SIZE += CATH_DSP_EMIT_DBUS(INSTR, NULL);
    }

    return TOTAL_SIZE;
}

UNK CATH_DSP_INSTRUCTION_DISASM(const SH_DSP_INSTRUCTION* INSTR, char* DEST)
{
    UNK TOTAL_SIZE = 0;
    char* BUFFER = DEST;

    const char* DSP_INSTR = CATH_GET_DSP_OPCODE_NAME(INSTR->INSTR_ID);
    UNK DSP_INSTR_LEN = strlen(DSP_INSTR);

    if(BUFFER)
    {
        memcpy(BUFFER, DSP_INSTR, DSP_INSTR_LEN);
        BUFFER += DSP_INSTR_LEN;
    }

    TOTAL_SIZE += DSP_INSTR_LEN;

    // FOR THOSE INSTRUCTIONS BY WHICH THE LENGTHS OF THE 
    // COMBINATORIAL INSTRUCTION PATTERNS HOUSE EITHER NOP OR END
    if(INSTR->DESCRIPTOR->IS_NOP || INSTR->DESCRIPTOR->IS_END)
    {
        // ONLY EMIT THE D BUS ACCESS IF THE CURRENT SLOT IS ACTIVE
        if(INSTR->IS_PARALLEL && INSTR->D_SLOT.IS_ACTIVE)
        {
            if(BUFFER) { BUFFER[0] = ' '; BUFFER[1] = ' '; BUFFER += 2; }
            TOTAL_SIZE += 2;

            UNK WRITTEN = CATH_DSP_EMIT_DBUS(INSTR, BUFFER);

            // THEN WE CAN ONLY BEGIN TO WRITE AFTER THE FACT
            if(BUFFER) BUFFER += WRITTEN;
            TOTAL_SIZE += WRITTEN;
        }

        if(BUFFER) *BUFFER = '\0';
        return TOTAL_SIZE;
    }

    // DO THE SAME WITH THE NON-ALU OPERANDS
    // IN THIS CASE, THEY WILL STILL USE THE SAME
    // DBUS ACCESS AS POVIDED GIVEN THE INSTRUCTION LAYOUTS
    
    if(BUFFER) { *BUFFER = ' '; BUFFER++; }
    TOTAL_SIZE++;

    UNK OPERAND_SIZE = CATH_DSP_INSTRUCTION_DISASM_OPERAND(INSTR, BUFFER);
    if(BUFFER) BUFFER += OPERAND_SIZE;
    TOTAL_SIZE += OPERAND_SIZE;

    if(INSTR->IS_PARALLEL && INSTR->D_SLOT.IS_ACTIVE)
    {
        if(BUFFER) { BUFFER[0] = ' '; BUFFER[1] = ' '; BUFFER += 2; }
        TOTAL_SIZE += 2;

        UNK WRITTEN = CATH_DSP_EMIT_DBUS(INSTR, BUFFER);
        if(BUFFER) BUFFER += WRITTEN;
        TOTAL_SIZE += WRITTEN;
    }

    if(BUFFER) *BUFFER = '\0';
    return TOTAL_SIZE;
}
