// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE DSP OPERANDS

// NESTED INCLUDES

#include "instructions/instructionDSP.h"
#include "instructions/operandsDSP.h"

// ACCESS THE CURRENT BUFFER SIZE FOR EACH DSP OPERAND
// FOLLOW THE SAME DESIGN PATTERN OF THE BASE OPERAND DEFINTION
UNK CATH_DSP_OPERAND_TYPE_GET_BUFFER_SIZE(SH_DSP_OPERAND_TYPE TYPE, const SH_DSP_INSTRUCTION* INSTR)
{
    // ASSIGN THE CALLBACK TO EACH RESPECTIVE TYPE
    SH_DSP_OPERAND_CALLBACK CB;
    CB = DSP_INSTR_CALLBACKS[TYPE];
    
    return CB(INSTR, NULL, 0);
}

UNK CATH_DSP_OPERAND_TYPE_DISASM(SH_DSP_OPERAND_TYPE TYPE, const struct SH_DSP_INSTRUCTION* INSTR, char* DEST)
{
    SH_DSP_OPERAND_CALLBACK CB;
    CB = DSP_INSTR_CALLBACKS[TYPE];
    
    return CB(INSTR, DEST, 64);
}

// DETERMINES ALL OF THE CONURRENT OPERANDS AND APPLIES
// THEM TO THE BUFFER
//
// A SIMILAR DESIGN PATTERN TO THE BASE DISASM OPERAND DEFINITION IS REUSED
// ALBEIT ONLY USED FOR TRACKING PARALLELISED INSTRUCTIONS 
UNK CATH_DSP_INSTRUCTION_DISASM_OPERAND(const SH_DSP_INSTRUCTION* INSTR, char* DEST)
{
    UNK TOTAL_SIZE = 0;
    UNK SLOT_COUNT = 0;

    // DETERMINE THE CURRENTLY USED SLOTS WITHIN THE DSP ITSELF
    // HELPS WITH DETERMINING THE CONDITIONS OF EACH RESPECTIVE "NTH_BUS"

    const SH_DSP_DESCRIPTOR* DSP_DESC = INSTR->DESCRIPTOR;

    // CACHE THE RESULT OF THE ALU MNEMONIC 
    // ONLY CONSUMED IF IS_ALU_OP IS SET
    const char* ALU_NAME = CATH_DSP_INSTR_ID_NAMES[INSTR->INSTR_ID];
    
    // CHECK FOR SPECICAL CASES BEFORE THE DEFINITION OF 
    // BUS LOCATION - HELPS WITH UNDERSTANDING THE LENGTH
    // OF THE OPCODE 

    if(DSP_DESC->IS_END) return snprintf(DEST, 64, "ENDI");
    if(DSP_DESC->IS_NOP) return snprintf(DEST, 64, "NOP");

    // 07/05/26 - INCURRED OVERHEAD FROM A DEDICATED
    // FUNCTION WHICH IS JUST A LARGE IF STATEMENT IS UNNECESSARY
    // 
    // THE FOLLOWING AIMS TO PROPERLY THE INPUT BEING EMITTERD FROM 
    // BUS OPERATIONS 

    if(DSP_DESC->X_BUS)
    {
        TOTAL_SIZE += snprintf(DEST + TOTAL_SIZE, 64 - TOTAL_SIZE,
                "%s", DSP_DESC->IS_ALU_OP ? ALU_NAME : "X");
    }

    if(DSP_DESC->D_BUS)
    {
        TOTAL_SIZE += snprintf(DEST + TOTAL_SIZE, 64 - TOTAL_SIZE,
                "%s", DSP_DESC->IS_ALU_OP ? ALU_NAME : "P");
    }

    if(DSP_DESC->Y_BUS)
    {
        TOTAL_SIZE += snprintf(DEST + TOTAL_SIZE, 64 - TOTAL_SIZE,
                "%s", DSP_DESC->IS_ALU_OP ? ALU_NAME : "Y");
    }
    
    if(DEST) DEST[TOTAL_SIZE] = '\0';
    return TOTAL_SIZE;
}

UNK CATH_DSP_OPERAND_TYPE_NONE(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    (void)BUFFER;
    (void)SIZE;
    return 0;
}
