// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS
//
// MORE SPECIFICALLY, THIS FILE ACCESSES ALL OF THE OPERAND FUNCTION CALLS
// AND TYPES, ACCESSES THE CURRENT STRING LITERAL OF THE OPERAND
// AND RETURNS ACCORDINGLY

// NESTED INCLUDES

#include "instructions/instructionDSP.h"
#include "instructions/operandsDSP.h"
#include "instructions/registerDSP.h"
#include "tables/tables.h"

// STATIC CONDITION NAME TABLES FOR ALL OF THE ENCOMPASSING 
// AREAS BY WHICH THEY ARE NEEDED FOR THE PURPOSES OF EVAUATING
// CONDITIONS AND OPERANDS ACCESS
STATIC const char* const SCU_DSP_MVI_COND_NAMES[][2] =
{
    [0x01] = { "Z",   "NZ"  },
    [0x02] = { "S",   "NS"  },
    [0x03] = { "ZS",  "NZS" },
    [0x04] = { "C",   "NC"  },
    [0x08] = { "T0",  "NT0" },
};

STATIC const char* const SCU_DSP_DMA_RAM_NAMES[4] = 
{
    [0x0] = "MC0",
    [0x1] = "MC1",
    [0x2] = "MC2",
    [0x3] = "MC3",
};

UNK CATH_DSP_OPERAND_TYPE_NONE(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    (void)BUFFER;
    (void)SIZE;
    return 0;
}

UNK CATH_DSP_OPERAND_TYPE_MC0(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_MC_NAME(0));
}

UNK CATH_DSP_OPERAND_TYPE_MC1(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_MC_NAME(1));
}

UNK CATH_DSP_OPERAND_TYPE_MC2(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_MC_NAME(2));
}

UNK CATH_DSP_OPERAND_TYPE_MC3(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_MC_NAME(3));
}

// THE FOLLOWING OPERATIONS SERVE TO EXTRACT ALL OF THE SORUCE FILED PACKS
// FROM BOTH THE RAM BANK AND CT COUNTER - ALL FOR THEIR RESPECTIVE BUS ACCESS

UNK CATH_DSP_OPERAND_TYPE_X(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 SRC = (U8)SCU_DSP_GET_SRC_X(INSTR);
    U8 RAM = SCU_DSP_GET_RAM_BANK(SRC);
    U8 CT = SCU_DSP_GET_CT(SRC);

    return snprintf(BUFFER, SIZE, "@%s+%s", 
        CATH_REGISTER_GET_RAM_ADDR_NAME(RAM), 
        CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_Y(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 SRC = (U8)SCU_DSP_GET_SRC_Y(INSTR);
    U8 RAM = SCU_DSP_GET_RAM_BANK(SRC);
    U8 CT = SCU_DSP_GET_CT(SRC);

    return snprintf(BUFFER, SIZE, "@%s+%s", 
        CATH_REGISTER_GET_RAM_ADDR_NAME(RAM), 
        CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_P(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 SRC = (U8)SCU_DSP_GET_SRC_D(INSTR);
    U8 RAM = SCU_DSP_GET_RAM_BANK(SRC);
    U8 CT = SCU_DSP_GET_CT(SRC);

    return snprintf(BUFFER, SIZE, "@%s+%s", 
        CATH_REGISTER_GET_RAM_ADDR_NAME(RAM), 
        CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_MUL(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "MUL");
}

UNK CATH_DSP_OPERAND_TYPE_ALU(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "ALU");
}

UNK CATH_DSP_OPERAND_TYPE_ACC(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    // ACCESS THE DESTINATION FIELD FROM BIT 0 FROM A0 AND A1
    U8 DEST = (U8)SCU_DSP_GET_DESTINATION(INSTR);
    return snprintf(BUFFER, SIZE, "%s", SCU_DSP_ACC_CMP_MASK(DEST) ? "A1" : "A0");
}

UNK CATH_DSP_OPERAND_TYPE_MVI_DEST(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 DEST = (U8)SCU_DSP_GET_MVI_DEST(INSTR);
    const char* NAME = CATH_DSP_MVI_DEST_NAMES[DEST];

    if(!NAME) NAME = "?";
    return snprintf(BUFFER, SIZE, "%s", NAME);
}

UNK CATH_DSP_OPERAND_TYPE_MVI_IMM(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U32 IMM = SCU_DSP_GET_MVI_COND_BIT(INSTR)
        ? SCU_DSP_GET_MVI_IMM_COND(INSTR)
        : SCU_DSP_GET_MVI_IMM_UNCOND(INSTR);

    return snprintf(BUFFER, SIZE, "#0x%X", IMM);
}

UNK CATH_DSP_OPERAND_TYPE_MVI_COND(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    if(!SCU_DSP_GET_MVI_COND_BIT(INSTR)) return 0;

    U8 STATUS = (U8)SCU_DSP_GET_MVI_STATUS(INSTR);
    bool NEGATE = (bool)SCU_DSP_GET_MVI_NEGATE(INSTR);

    if(STATUS >= SCU_DSP_MVI_COND_MAX) return 0;
    if(!SCU_DSP_MVI_COND_NAMES[STATUS][0]) return 0;

    return snprintf(BUFFER, SIZE, ",%s", SCU_DSP_MVI_COND_NAMES[STATUS][NEGATE]);
}

UNK CATH_DSP_OPERAND_TYPE_RAM0_ADDR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "RAM0");
}

UNK CATH_DSP_OPERAND_TYPE_RAM1_ADDR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "RAM1");
}

UNK CATH_DSP_OPERAND_TYPE_RAM2_ADDR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "RAM2");
}

UNK CATH_DSP_OPERAND_TYPE_RAM3_ADDR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "RAM3");
}

UNK CATH_DSP_OPERAND_TYPE_RAM0(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 SRC = (U8)SCU_DSP_GET_SRC_D(INSTR);
    U8 CT = SCU_DSP_GET_CT(SRC);
    return snprintf(BUFFER, SIZE, "@RAM0+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_RAM1(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 SRC = (U8)SCU_DSP_GET_SRC_D(INSTR);
    U8 CT = SCU_DSP_GET_CT(SRC);
    return snprintf(BUFFER, SIZE, "@RAM1+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_RAM2(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 SRC = (U8)SCU_DSP_GET_SRC_D(INSTR);
    U8 CT = SCU_DSP_GET_CT(SRC);
    return snprintf(BUFFER, SIZE, "@RAM2+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_RAM3(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 SRC = (U8)SCU_DSP_GET_SRC_D(INSTR);
    U8 CT = SCU_DSP_GET_CT(SRC);
    return snprintf(BUFFER, SIZE, "@RAM3+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_CT0(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_CT_NAME(0));
}

UNK CATH_DSP_OPERAND_TYPE_CT1(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_CT_NAME(1));
}

UNK CATH_DSP_OPERAND_TYPE_CT2(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_CT_NAME(2));
}

UNK CATH_DSP_OPERAND_TYPE_CT3(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_CT_NAME(3));
}

UNK CATH_DSP_OPERAND_TYPE_RX(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "RX");
}

UNK CATH_DSP_OPERAND_TYPE_RY(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "RY");
}
    
UNK CATH_DSP_OPERAND_TYPE_ALL(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "ALL");
}

UNK CATH_DSP_OPERAND_TYPE_PC(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 ADDRESS = (U8)SCU_DSP_GET_JUMP_ADDR(INSTR);
    return snprintf(BUFFER, SIZE, "0x%02X", ADDRESS);
}

UNK CATH_DSP_OPERAND_TYPE_TOP(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "TOP");
}

UNK CATH_DSP_OPERAND_TYPE_LOP(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "LOP");
}

UNK CATH_DSP_OPERAND_TYPE_IMM(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 IMM = (U8)SCU_DSP_GET_IMM(INSTR);
    return snprintf(BUFFER, SIZE, "#0x%02X", IMM);
}

UNK CATH_DSP_OPERAND_TYPE_IMM_DISP(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    S8 DISP = (S8)SCU_DSP_GET_JUMP_ADDR(INSTR);
    U32 TARGET = INSTR->PC + (S32)DISP;
    return snprintf(BUFFER, SIZE, "0x%08X", TARGET);
}

UNK CATH_DSP_OPERAND_TYPE_AT_RAM0_ADR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 DEST = (U8)SCU_DSP_GET_DESTINATION(INSTR);
    U8 CT = SCU_DSP_GET_CT(DEST);
    return snprintf(BUFFER, SIZE, "@RAM0+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_AT_RAM1_ADR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 DEST = (U8)SCU_DSP_GET_DESTINATION(INSTR);
    U8 CT = SCU_DSP_GET_CT(DEST);
    return snprintf(BUFFER, SIZE, "@RAM1+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_AT_RAM2_ADR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 DEST = (U8)SCU_DSP_GET_DESTINATION(INSTR);
    U8 CT = SCU_DSP_GET_CT(DEST);
    return snprintf(BUFFER, SIZE, "@RAM2+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_AT_RAM3_ADR(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 DEST = (U8)SCU_DSP_GET_DESTINATION(INSTR);
    U8 CT = SCU_DSP_GET_CT(DEST);
    return snprintf(BUFFER, SIZE, "@RAM3+%s", CATH_REGISTER_GET_CT_NAME(CT));
}

UNK CATH_DSP_OPERAND_TYPE_DMA(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    U8 CHANNEL = (U8)SCU_DSP_GET_DMA_CHANNEL(INSTR);
    U8 RAM     = (U8)SCU_DSP_GET_DMA_RAM(INSTR);
    U8 COUNT   = (U8)SCU_DSP_GET_DMA_COUNT(INSTR);

    const char* CHANNEL_NAME  = CHANNEL ? "D1" : "D0";
    const char* RAM_NAME = SCU_DSP_DMA_RAM_NAMES[RAM];

    if(!RAM_NAME) RAM_NAME = "?";

    if(!CHANNEL)
        return snprintf(BUFFER, SIZE, "%s, %s, #0x%X", CHANNEL_NAME, RAM_NAME, COUNT);
    
    return snprintf(BUFFER, SIZE, "%s, %s, #0x%X", RAM_NAME, CHANNEL_NAME, COUNT);
}
