// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS
//
// MORE SPECIFICALLY, THIS FILE ACCESSES ALL OF THE OPERAND FUNCTION CALLS
// AND TYPES, ACCESSES THE CURRENT STRING LITERAL OF THE OPERAND
// AND RETURNS ACCORDINGLY

// NESTED INCLUDES

#include "instructions/instructionDSP.h"
#include "instructions/operandsDSP.h"
#include "instructions/registerDSP.h"
#include "tables/tables.h"

UNK CATH_DSP_OPERAND_TYPE_NONE(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    (void)BUFFER;
    (void)SIZE;
    return 0;
}

UNK CATH_DSP_OPERAND_TYPE_MC0(const struct SH_DSP_INSTRUCTION* INSTR, char* BUFFER, UNK SIZE)
{
    (void)INSTR;
    return snprintf(BUFFER, SIZE, "%s", CATH_REGISTER_GET_MC_NAME(0));
}