// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE REGISTERS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE REGISTERS OF THE DSP

// NESTED INCLUDES

#include "instructions/registerDSP.h"

// SYSTEM INCLUDES

#include <assert.h>

// ACCESS ALL OF THE CONCURRENT REGISTER NAMES FROM THE ENUM
// MIRROR THE EXACT DESIGN PATTERN OF THE BASELINE REGISTER NAME ACCESS
const char* CATH_REGISTER_GET_MC_NAME(U8 VALUE)
{
    assert(VALUE < DSP_REG_MC_MAX);
}