// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE DESCRIPTORS FOR EACH INSTRUCTION TYPE
// SPECIFICALLY FOCUSSED ON THE DSP

// NESTED INCLUDES

#include "instructions/instructionDSP.h"

// THE INTRINSIC VALUE OF THE DSP ITSELF IS THAT RATHER THAN ACCOUNTING 
// FOR THE STATIC AND DETERMINISTIC RESULTS OF INSTRUCTION CHARACTERISTICS
// THE DSP LEVERAGES A PARALLELISED APPROACH
//
// EACH OF THE FOLLOWING DESCRIPTORS AGAINST THEIR RESPECTIVE ENUM VALUE
// WILL PROVIDE A TEMPLATE OF SORTS - WHICH WILL BE EVALUATED AT RUNTIME
// BASED ON THEIR RESPECTIVE VALUE WITHIN DATA RAM

const SH_DSP_DESCRIPTOR DSP_DESCRIPTORS[CATH_INSTR_ID_DSP_ALL_MAX] = 
{
    [CATH_INSTR_ID_DSP_INVALID] = 
    {
        .X_BUS_SRC = DSP_OPERAND_NONE,
        .Y_BUS_SRC = DSP_OPERAND_NONE,
        .D_BUS_SRC = DSP_OPERAND_NONE,
        .DEST = DSP_OPERAND_NONE,
        .IS_NOP = true,
        .IS_ALU_OP = false,
    },

    [CATH_INSTR_ID_DSP_AD2] = 
    {
        .X_BUS_SRC = DSP_OPERAND_NONE,
        .Y_BUS_SRC = DSP_OPERAND_NONE,
        .D_BUS_SRC = DSP_OPERAND_NONE,
        .DEST = DSP_OPERAND_ACC,
        .IS_ALU_OP = true,
        .IS_MULTIPLY = false,
        .IS_MOVE = true,
    },

    [CATH_INSTR_ID_DSP_ADD] = 
    {
        .X_BUS_SRC = DSP_OPERAND_NONE,
        .Y_BUS_SRC = DSP_OPERAND_NONE,
        .D_BUS_SRC = DSP_OPERAND_NONE,
        .DEST = DSP_OPERAND_ACC,
        .IS_ALU_OP = true,
        .IS_MULTIPLY = false,
        .IS_MOVE = true,
    },
};