// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE OPERANDS OF THE DSP

// NESTED INCLUDES

#include "instructions/instructionDSP.h"
#include "instructions/operandsDSP.h"
#include "instructions/registerDSP.h"

const SH_DSP_OPERAND_CALLBACK DSP_INSTR_CALLBACKS[DSP_OPERAND_MAX] = 
{
    [DSP_OPERAND_NONE]                      = CATH_DSP_OPERAND_TYPE_NONE,
    [DSP_OPERAND_MC0]                       = CATH_DSP_OPERAND_TYPE_MC0,
    [DSP_OPERAND_MC1]                       = CATH_DSP_OPERAND_TYPE_MC1,
    [DSP_OPERAND_MC2]                       = CATH_DSP_OPERAND_TYPE_MC2,
    [DSP_OPERAND_MC3]                       = CATH_DSP_OPERAND_TYPE_MC3,
};
