// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE OPERANDS

// NESTED INCLUDES

#include "instructions/operands.h"

const SH2_OPERAND_CALLBACK INSTR_CALLBACKS[OPERAND_MAX] = 
{
    [OPERAND_NONE]              = CATH_OPERAND_TYPE_NONE,
    [OPERAND_IMM]               = CATH_OPERAND_TYPE_IMM,
    [OPERAND_RN]                = CATH_OPERAND_TYPE_RN,
    [OPERAND_RM]                = CATH_OPERAND_TYPE_RM,
    [OPERAND_AT_RN]             = CATH_OPERAND_TYPE_AT_RN,
    [OPERAND_AT_RM]             = CATH_OPERAND_TYPE_AT_RM,
    [OPERAND_AT_RN_POST_INC]    = CATH_OPERAND_TYPE_AT_RN_POST_INC,
    [OPERAND_AT_RN_PRE_DEC]     = CATH_OPERAND_TYPE_AT_RN_PRE_DEC,
    [OPERAND_AT_RM_POST_INC]    = CATH_OPERAND_TYPE_AT_RM_POST_INC,
    [OPERAND_AT_R0_RN]          = CATH_OPERAND_TYPE_AT_R0_RN,
    [OPERAND_AT_R0_RM]          = CATH_OPERAND_TYPE_AT_R0_RM,
    [OPERAND_AT_DISP_GBR]       = CATH_OPERAND_TYPE_AT_DISP_GBR,
    [OPERAND_AT_R0_GBR]         = CATH_OPERAND_TYPE_AT_R0_GBR,
    [OPERAND_AT_DISP_PC]        = CATH_OPERAND_TYPE_AT_DISP_PC,
    [OPERAND_DISP_PC]           = CATH_OPERAND_TYPE_DISP_PC,
    [OPERAND_SR]                = CATH_OPERAND_TYPE_SR,
    [OPERAND_GBR]               = CATH_OPERAND_TYPE_GBR,
    [OPERAND_VBR]               = CATH_OPERAND_TYPE_VBR,
    [OPERAND_MACH]              = CATH_OPERAND_TYPE_MACH,
    [OPERAND_MACL]              = CATH_OPERAND_TYPE_MACL,
    [OPERAND_PR]                = CATH_OPERAND_TYPE_PR,
};