// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE OPERAND
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE OPERANDS OF THE DSP

// NESTED INCLUDES

#include "instructions/instructionDSP.h"
#include "instructions/operandsDSP.h"
#include "instructions/registerDSP.h"

const SH_DSP_OPERAND_CALLBACK DSP_INSTR_CALLBACKS[DSP_OPERAND_MAX] = 
{
    [DSP_OPERAND_NONE]                      = CATH_DSP_OPERAND_TYPE_NONE,
    [DSP_OPERAND_MC0]                       = CATH_DSP_OPERAND_TYPE_MC0,
    [DSP_OPERAND_MC1]                       = CATH_DSP_OPERAND_TYPE_MC1,
    [DSP_OPERAND_MC2]                       = CATH_DSP_OPERAND_TYPE_MC2,
    [DSP_OPERAND_MC3]                       = CATH_DSP_OPERAND_TYPE_MC3,
    [DSP_OPERAND_X]                         = CATH_DSP_OPERAND_TYPE_X,
    [DSP_OPERAND_Y]                         = CATH_DSP_OPERAND_TYPE_Y,
    [DSP_OPERAND_P]                         = CATH_DSP_OPERAND_TYPE_P,
    [DSP_OPERAND_MUL]                       = CATH_DSP_OPERAND_TYPE_MUL,
    [DSP_OPERAND_ALU]                       = CATH_DSP_OPERAND_TYPE_ALU,
    [DSP_OPERAND_A]                         = CATH_DSP_OPERAND_TYPE_ALU,
    [DSP_OPERAND_ACC]                       = CATH_DSP_OPERAND_TYPE_ACC,
    [DSP_OPERAND_MVI_DEST]                  = CATH_DSP_OPERAND_TYPE_MVI_DEST,
    [DSP_OPERAND_MVI_IMM]                   = CATH_DSP_OPERAND_TYPE_MVI_IMM,
    [DSP_OPERAND_MVI_COND]                  = CATH_DSP_OPERAND_TYPE_MVI_COND,
    [DSP_OPERAND_JMP_COND]                  = CATH_DSP_OPERAND_TYPE_JMP_COND,
    [DSP_OPERAND_RAM0_ADDR]                 = CATH_DSP_OPERAND_TYPE_RAM0_ADDR,
    [DSP_OPERAND_RAM1_ADDR]                 = CATH_DSP_OPERAND_TYPE_RAM1_ADDR,
    [DSP_OPERAND_RAM2_ADDR]                 = CATH_DSP_OPERAND_TYPE_RAM2_ADDR,
    [DSP_OPERAND_RAM3_ADDR]                 = CATH_DSP_OPERAND_TYPE_RAM3_ADDR,
    [DSP_OPERAND_RAM0_DATA]                 = CATH_DSP_OPERAND_TYPE_RAM0,
    [DSP_OPERAND_RAM1_DATA]                 = CATH_DSP_OPERAND_TYPE_RAM1,
    [DSP_OPERAND_RAM2_DATA]                 = CATH_DSP_OPERAND_TYPE_RAM2,
    [DSP_OPERAND_RAM3_DATA]                 = CATH_DSP_OPERAND_TYPE_RAM3,
    [DSP_OPERAND_CT0]                       = CATH_DSP_OPERAND_TYPE_CT0,
    [DSP_OPERAND_CT1]                       = CATH_DSP_OPERAND_TYPE_CT1,
    [DSP_OPERAND_CT2]                       = CATH_DSP_OPERAND_TYPE_CT2,
    [DSP_OPERAND_CT3]                       = CATH_DSP_OPERAND_TYPE_CT3,
    [DSP_OPERAND_RX]                        = CATH_DSP_OPERAND_TYPE_RX,
    [DSP_OPERAND_RY]                        = CATH_DSP_OPERAND_TYPE_RY,
    [DSP_OPERAND_STORE]                     = CATH_DSP_OPERAND_TYPE_ALL,
    [DSP_OPERAND_PC]                        = CATH_DSP_OPERAND_TYPE_PC,
    [DSP_OPERAND_TOP]                       = CATH_DSP_OPERAND_TYPE_TOP,
    [DSP_OPERAND_LOP]                       = CATH_DSP_OPERAND_TYPE_LOP,
    [DSP_OPERAND_IMM]                       = CATH_DSP_OPERAND_TYPE_IMM,
    [DSP_OPERAND_IMM_DISP]                  = CATH_DSP_OPERAND_TYPE_IMM_DISP,
    [DSP_OPERAND_AT_RAM0_ADDR]              = CATH_DSP_OPERAND_TYPE_AT_RAM0_ADR,
    [DSP_OPERAND_AT_RAM1_ADDR]              = CATH_DSP_OPERAND_TYPE_AT_RAM1_ADR,
    [DSP_OPERAND_AT_RAM2_ADDR]              = CATH_DSP_OPERAND_TYPE_AT_RAM2_ADR,
    [DSP_OPERAND_AT_RAM3_ADDR]              = CATH_DSP_OPERAND_TYPE_AT_RAM3_ADR,
    [DSP_OPERAND_DMA]                       = CATH_DSP_OPERAND_TYPE_DMA,
};
