// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE MODULARISATION AND LAYOUT OF THE REGISTERS
// IDENTIFIERS, THEIR RESPECTIVE CHARACTERISTICS, THE CONCATENATION OF TYPES
// AND HELPER FUNCTIONS - ALL PERTAINING TOWARDS THE REGISTERS

// NESTED INCLUDES  

#include "instructions/registerDSP.h"

#define USE_CATH_DSP_REG

// RESOLVE A 3-BIT MC FIELD DEPENDING ON BUS ACCESS
// TO DETERMINE THE REGISTER NAME
//
// USED BY X/Y/D BUS SOURCE OPERANDS
const char* CATH_DSP_MC_NAMES[DSP_REG_MC_MAX][2] =
{
    [DSP_REG_MC0]   =   { "MC0", "mc0" },
    [DSP_REG_MC1]   =   { "MC1", "mc1" },
    [DSP_REG_MC2]   =   { "MC2", "mc2" },
    [DSP_REG_MC3]   =   { "MC3", "mc3" },
};

const char* CATH_DSP_CT_NAMES[DSP_REG_CT_MAX][2] =
{
    [DSP_REG_CT0]   =   { "CT0", "ct0" },
    [DSP_REG_CT1]   =   { "CT1", "ct1" },
    [DSP_REG_CT2]   =   { "CT2", "ct2" },
    [DSP_REG_CT3]   =   { "CT3", "ct3" },
};

const char* CATH_DSP_RA_NAMES[DSP_REG_RA_MAX] =
{
    [DSP_REG_RA0]   =   { "RAM0" },
    [DSP_REG_RA1]   =   { "RAM1" },
    [DSP_REG_RA2]   =   { "RAM2" },
    [DSP_REG_RA3]   =   { "RAM3" },
};
