// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SUPERH INSTRUCTION DECODER

// THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY ENCOMPASSING THE CREATION OF TABLES
// RELATING TO CHARACTERISTICS OF THE ARCHITECTURE

// HELPS WITH BEING ABLE TO NEGATE MATICULOUS CREATION OF ASSETS

// NESTED INCLUDES

#include "tables/tables.h"

// DEFINE THE BASIS FOR ANY AND ALL MACROS PERTAINING TOWARDS TABLE GEN

#define         DISP_SCALE_ENTRY(INSTR_ID, SCALE)       [INSTR_ID] = SCALE,

const U8 CATH_DISP_SCALE[CATH_INSTR_ID_ALL_MAX] = 
{
        #include "tables/disp_scale.inc"
};

#undef DISP_SCALE_ENTRY
